"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user, AnonymousUserMixin
from flask_user import current_user
from dtm import *
from project import *
from instrumentation import Restrict, PrivacyException
from flask_principal import Identity, identity_changed, AnonymousIdentity
from implicits import implicits
from werkzeug.datastructures import MultiDict

RESTRICTED = Restrict()

def find_personal_data(resource, subresource):
    pds = list(PersonalData.query.all())
    for pd in pds:
        if pd.resource == resource and pd.subresource == subresource:
            return pd
    return None

def add_consent(user, purpose, resource, subresource):
    pd = find_personal_data(resource, subresource)
    p = Purpose.query.filter_by(name=purpose).first()
    c = Consent(data=pd, user=user)
    c.purposes.append(p)
    db.session.add(c)
    db.session.commit()

# This test suite is dedicated for PRIVACY tests

# Test Case 11: Accept a received invitation
# on endpoint accept_invitation()
# Should fail
def test_case_11_accept_invitation_FUNCTIONAL(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(caller, FUNCTIONAL, 'Person', 'attends')
        except Exception:
            assert False
        # Test accept_invitation()
        try:
            from project import accept_invitation
            accept_invitation(12)  
        except PrivacyException:
            assert False
        finally:
            assert Invite.query.filter(Invite.id == 12).count() == 0
            assert caller.id in [p.id for p in Event.query.get(9).attendants]
            db.session.rollback()

# Test Case 18: Read own attended events, more than 2 attended events
# on endpoint personalized_stats()
# Should fail
def test_case_18_personalized_stats_INSIGHTS(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(caller, INSIGHTS, 'Person', 'attends')
        except Exception:
            assert False
        # Test personalized_stats()
        try:
            from project import personalized_stats
            result = personalized_stats(caller.id)
            assert result['attended_events'] is not RESTRICTED
            assert len(result['attended_events']) == 4
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 20: Read own subscriptions, more than 2 attended events
# on endpoint personalized_stats()
# Should fail
def test_case_20_personalized_stats_INSIGHTS(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(caller, INSIGHTS, 'Person', 'subscriptions')
        except Exception:
            assert False
        # Test personalized_stats()
        try:
            from project import personalized_stats
            result = personalized_stats(caller.id)
            assert result['subscriptions'] is not RESTRICTED
            assert len(result['subscriptions']) == 1
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 18b: Read own attended events, less or equal to 2 attended events
# on endpoint personalized_stats()
# Should fail
def test_case_18b_personalized_stats_INSIGHTS(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(caller, INSIGHTS, 'Person', 'attends')
        except Exception:
            assert False
        # Test personalized_stats()
        try:
            from project import personalized_stats
            result = personalized_stats(caller.id)
            assert result['attended_events'] == RESTRICTED or len(result['attended_events']) == 0
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 20b: Read own subscriptions, less or equal to 2 attended events
# on endpoint personalized_stats()
# Should fail
def test_case_20b_personalized_stats_INSIGHTS(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(caller, INSIGHTS, 'Person', 'attends')
        except Exception:
            assert False
        # Test personalized_stats()
        try:
            from project import personalized_stats
            result = personalized_stats(caller.id)
            assert result['subscriptions'] == RESTRICTED or len(result['subscriptions']) == 0
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 11: Accept a received invitation
# on endpoint accept_invitation()
# Should fail
def test_case_11_accept_invitation_ANY(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(caller, ANY, 'Person', 'attends')
        except Exception:
            assert False
        # Test accept_invitation()
        try:
            from project import accept_invitation
            accept_invitation(12)  
        except PrivacyException:
            assert False
        finally:
            assert Invite.query.filter(Invite.id == 12).count() == 0
            assert caller.id in [p.id for p in Event.query.get(9).attendants]
            db.session.rollback()

# Test Case 18: Read own attended events, more than 2 attended events
# on endpoint personalized_stats()
# Should fail
def test_case_18_personalized_stats_ANY(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(caller, ANY, 'Person', 'attends')
        except Exception:
            assert False
        # Test personalized_stats()
        try:
            from project import personalized_stats
            result = personalized_stats(caller.id)
            assert result['attended_events'] is not RESTRICTED
            assert len(result['attended_events']) == 4
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 20: Read own subscriptions, more than 2 attended events
# on endpoint personalized_stats()
# Should fail
def test_case_20_personalized_stats_ANY(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(caller, ANY, 'Person', 'subscriptions')
        except Exception:
            assert False
        # Test personalized_stats()
        try:
            from project import personalized_stats
            result = personalized_stats(caller.id)
            assert result['subscriptions'] is not RESTRICTED
            assert len(result['subscriptions']) == 1
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 18b: Read own attended events, less or equal to 2 attended events
# on endpoint personalized_stats()
# Should fail
def test_case_18b_personalized_stats_ANY(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(caller, ANY, 'Person', 'attends')
        except Exception:
            assert False
        # Test personalized_stats()
        try:
            from project import personalized_stats
            result = personalized_stats(caller.id)
            assert result['attended_events'] == RESTRICTED or len(result['attended_events']) == 0
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 20b: Read own subscriptions, less or equal to 2 attended events
# on endpoint personalized_stats()
# Should fail
def test_case_20b_personalized_stats_ANY(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(caller, ANY, 'Person', 'attends')
        except Exception:
            assert False
        # Test personalized_stats()
        try:
            from project import personalized_stats
            result = personalized_stats(caller.id)
            assert result['subscriptions'] == RESTRICTED or len(result['subscriptions']) == 0
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()