"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user, AnonymousUserMixin
from flask_user import current_user
from dtm import *
from project import *
from instrumentation import Restrict, PrivacyException
from flask_principal import Identity, identity_changed, AnonymousIdentity
from implicits import implicits
from werkzeug.datastructures import MultiDict

RESTRICTED = Restrict()

def find_personal_data(resource, subresource):
    pds = list(PersonalData.query.all())
    for pd in pds:
        if pd.resource == resource and pd.subresource == subresource:
            return pd
    return None

def add_consent(user, purpose, resource, subresource):
    pd = find_personal_data(resource, subresource)
    p = Purpose.query.filter_by(name=purpose).first()
    c = Consent(data=pd, user=user)
    c.purposes.append(p)
    db.session.add(c)
    db.session.commit()

# This test suite is dedicated for PRIVACY tests

# Test Case 6: Read one’s own name
# on endpoint users() 
# Should fail
def test_case_6_users_FUNCTIONAL(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(caller, FUNCTIONAL, 'Person', 'name')
        except Exception:
            assert False
        # Test users()
        try:
            from project import users
            result = users()
            assert result['current_user_name'] != RESTRICTED
            assert result['current_user_name'] is not None
            assert result['current_user_name'] == caller.name
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 17: Read other Person’s gender
# on endpoint user() 
# Should fail
def test_case_17_user_ANY(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(owner, ANY, 'Person', 'gender')
        except Exception:
            assert False
        # Test user()
        try:
            from project import user
            result = user(5)
            assert result['user_gender'] != RESTRICTED
            assert result['user_gender'] is not None
            assert result['user_gender'] == 'male'
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 20: Read other Person’s email (caller: moderator, this person subscribes)
# on endpoint user() 
# Should fail
def test_case_20_user_ANY(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR1').one()
    owner = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(owner, ANY, 'Person', 'email')
        except Exception:
            assert False
        # Test user()
        try:
            from project import user
            result = user(5)
            assert result['user_email'] != RESTRICTED
            assert result['user_email'] is not None
            assert result['user_email'] == 'p1@gmail.com'
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

