"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user, AnonymousUserMixin
from flask_user import current_user
from dtm import *
from project import *
from instrumentation import Restrict, PrivacyException
from flask_principal import Identity, identity_changed, AnonymousIdentity
from implicits import implicits
from werkzeug.datastructures import MultiDict

RESTRICTED = Restrict()

def find_personal_data(resource, subresource):
    pds = list(PersonalData.query.all())
    for pd in pds:
        if pd.resource == resource and pd.subresource == subresource:
            return pd
    return None

def add_consent(user, purpose, resource, subresource):
    pd = find_personal_data(resource, subresource)
    p = Purpose.query.filter_by(name=purpose).first()
    c = Consent(data=pd, user=user)
    c.purposes.append(p)
    db.session.add(c)
    db.session.commit()

# This test suite is dedicated for PRIVACY tests

# Test Case 175: Read an Event’s attendants’ surname field that one does not own, manage, attend, or request
# on endpoint manage_event() 
# Should fail
def test_case_175_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'p0').one()
    owner2 = Person.query.filter(Person.testid == 'p3').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(owner1, CORE, 'Person', 'surname')
            add_consent(owner2, CORE, 'Person', 'surname')
        except Exception:
            assert False
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(13)
            assert result['event_attendant_surnames'] != RESTRICTED
            assert len(result['event_attendant_surnames']) == 2
            assert set(result['event_attendant_surnames']) == set(['p0', 'p3'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 183: Read an Event’s managedBy’ name field that one attends
# on endpoint manage_event() 
# Should fail
def test_case_183_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(owner, CORE, 'Person', 'name')
        except Exception:
            assert False
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(11)
            assert result['event_manager_names'] != RESTRICTED
            assert len(result['event_manager_names']) == 1
            assert set(result['event_manager_names']) == set(['p0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 184: Read an Event’s managedBy’ name field that one requests
# on endpoint manage_event() 
# Should fail
def test_case_184_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(owner, CORE, 'Person', 'name')
        except Exception:
            assert False
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(12)
            assert result['event_manager_names'] != RESTRICTED
            assert len(result['event_manager_names']) == 1
            assert set(result['event_manager_names']) == set(['p0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

