"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user, AnonymousUserMixin
from flask_user import current_user
from model import *
from project import *
from dto import RESTRICTED
from flask_principal import Identity, identity_changed, AnonymousIdentity
from implicits import implicits
from werkzeug.datastructures import MultiDict

# This test suite is dedicated for PRIVACY tests.

PURPOSES = [
    AnyPurpose,
    FunctionalPurpose,
    MarketingPurpose,
    AnalyticsPurpose,
    CorePurpose,
    RecommendEventsPurpose,
    TargetedMarketingPurpose,
    MassMarketingPurpose,
    InsightsPurpose,
    StatsPurpose
]

def revoke_consent(user,purpose,resource,subresource):
    my_purpose = Purpose.query.filter_by(name=purpose).first()
    consents = Consent.query.filter_by(person_id=user.id, purpose_id=my_purpose.id, classname=resource, propertyname=subresource).all()
    for consent in consents:
        db.session.delete(consent)

def grant_consent(user,purpose,resource,subresource):
    my_purpose = Purpose.query.filter_by(name=purpose).first()
    db.session.add(Consent(classname=resource,propertyname=subresource,user=user,purpose=my_purpose))
    db.session.commit()

# This test suite is dedicated for PRIVACY tests
def is_response(result):
    return type(result) == Response
    
@implicits("app_with_data")
def login_user(user, app_with_data):
    from flask_login import login_user
    login_user(user)
    identity_changed.send(app_with_data, identity=Identity(current_user.id))

# Test Case 231: Remove oneself from attending an Event that one attends
# on endpoint remove_attendee() 
# Should pass
def test_case_231_remove_attendee(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","attends")
        except Exception:
            assert False
        # Test remove_attendee()
        try:
            from project import remove_attendee
            remove_attendee(caller.id,12)
            assert caller.id not in [attendee.id for attendee in Event.query.get(12).attendants]
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 234: Remove other attendants from an Event that one owns
# on endpoint remove_attendee() 
# Should pass
def test_case_234_remove_attendee(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.get(5)
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner,CorePurpose,"Person","attends")
        except Exception:
            assert False
        # Test remove_attendee()
        try:
            from project import remove_attendee
            remove_attendee(5,10)
            assert 5 not in [attendee.id for attendee in Event.query.get(10).attendants]
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 235: Remove other attendants from an Event that one manages
# on endpoint remove_attendee() 
# Should pass
def test_case_235_remove_attendee(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.get(5)
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner,CorePurpose,"Person","attends")
        except Exception:
            assert False
        # Test remove_attendee()
        try:
            from project import remove_attendee
            remove_attendee(5,11)
            assert 5 not in [attendee.id for attendee in Event.query.get(11).attendants]
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 241: Accept an attendance request for an Event as an owner
# on endpoint accept_request() 
# Should pass
def test_case_241_accept_request(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.get(7)
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner,CorePurpose,"Person","attends")
        except Exception:
            assert False
        # Test accept_request()
        try:
            from project import accept_request
            result = accept_request(7,10)
            assert 7 not in [requestor.id for requestor in Event.query.get(10).requesters]
            assert 7 in [attendee.id for attendee in Event.query.get(10).attendants]
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 242: Accept an attendance request for an Event as a manager
# on endpoint accept_request() 
# Should pass
def test_case_242_accept_request(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.get(7)
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner,CorePurpose,"Person","attends")
        except Exception:
            assert False
        # Test accept_request()
        try:
            from project import accept_request
            result = accept_request(7,11)
            assert 7 not in [requestor.id for requestor in Event.query.get(11).requesters]
            assert 7 in [attendee.id for attendee in Event.query.get(11).attendants]
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()