"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user, AnonymousUserMixin
from flask_user import current_user
from model import db
from project import *
from dto import RESTRICTED
from flask_principal import Identity, identity_changed, AnonymousIdentity
from implicits import implicits
from werkzeug.datastructures import MultiDict

# This test suite is dedicated for PRIVACY tests.

def is_response(result):
    return type(result) == Response
    
@implicits("app_with_data")
def login_user(user, app_with_data):
    from flask_login import login_user
    login_user(user)
    identity_changed.send(app_with_data, identity=Identity(current_user.id))

# Test Case 56: Edit one’s own role from Admin to Moderator
# on endpoint update_user()
# Should fail
def test_case_56_update_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN56').one()
    with app_with_data.test_request_context():
        login_user(caller)
        request.form = MultiDict({
            "id": caller.id,
            "name": caller.name,
            "surname": caller.surname,
            "role": "MODERATOR",
            "email": caller.email,
            "gender": caller.gender
        })
        try:
            from project import update_user
            update_user()
        except PrivacyException:
            assert True
        finally:
            assert Person.query.get(caller.id).role.name == "ADMIN"
            db.session.rollback()

# Test Case 58: Edit other Person’s role from Regularuser to Admin
# on endpoint update_user()
# Should fail
def test_case_58_update_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    target = Person.query.filter(Person.testid == 'FREEUSER58').one()
    with app_with_data.test_request_context():
        login_user(caller)
        request.form = MultiDict({
            "id": target.id,
            "name": target.name,
            "surname": target.surname,
            "role": "ADMIN",
            "email": target.email,
            "gender": target.gender
        })
        try:
            from project import update_user
            update_user()
        except PrivacyException:
            assert True
        finally:
            assert Person.query.get(target.id).role.name == "REGULARUSER"
            db.session.rollback()

# Test Case 61: Edit other Person’s role from Admin to Regularuser
# on endpoint update_user()
# Should fail
def test_case_61_update_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    target = Person.query.filter(Person.testid == 'ADMIN61').one()
    with app_with_data.test_request_context():
        login_user(caller)
        request.form = MultiDict({
            "id": target.id,
            "name": target.name,
            "surname": target.surname,
            "role": "REGULARUSER",
            "email": target.email,
            "gender": target.gender
        })
        try:
            from project import update_user
            update_user()
        except PrivacyException:
            assert True
        finally:
            assert Person.query.get(target.id).role.name == "ADMIN"
            db.session.rollback()

