"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user, AnonymousUserMixin
from flask_user import current_user
from model import *
from project import *
from dto import RESTRICTED
from flask_principal import Identity, identity_changed, AnonymousIdentity
from implicits import implicits

# This test suite is dedicated for PRIVACY tests.

PURPOSES = [
    AnyPurpose,
    FunctionalPurpose,
    MarketingPurpose,
    AnalyticsPurpose,
    CorePurpose,
    RecommendEventsPurpose,
    TargetedMarketingPurpose,
    MassMarketingPurpose
]

def revoke_consent(user,purpose,resource,subresource):
    my_purpose = Purpose.query.filter_by(name=purpose).first()
    consents = Consent.query.filter_by(person_id=user.id, purpose_id=my_purpose.id, classname=resource, propertyname=subresource).all()
    for consent in consents:
        db.session.delete(consent)

def grant_consent(user,purpose,resource,subresource):
    my_purpose = Purpose.query.filter_by(name=purpose).first()
    db.session.add(Consent(classname=resource,propertyname=subresource,user=user,purpose=my_purpose))
    db.session.commit()

def is_response(result):
    return type(result) == Response
    
@implicits("app_with_data")
def login_user(user, app_with_data):
    from flask_login import login_user
    login_user(user)
    identity_changed.send(app_with_data, identity=Identity(current_user.id))

# Test Case 1: Read one’s own name
# on endpoint main() 
# Should pass
def test_case_1_Functional_main(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,FunctionalPurpose,"Person","name")
        except Exception:
            assert False
        # Test main()
        try:
            from project import main
            result = main()
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['name'] is not RESTRICTED
                assert testing_user['name'] is not None
                assert testing_user['name'] == caller.name
            else:
                assert testing_user.name is not RESTRICTED
                assert testing_user.name is not None
                assert testing_user.name == caller.name 
        except SecurityException:
            assert False
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 16: Read one’s own gender
# on endpoint user() 
# Should pass
def test_case_16_Functional_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,FunctionalPurpose,"Person","gender")
        except Exception:
            assert False
        # Test user()
        try:
            from project import user
            result = user(4)
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['gender'] is not RESTRICTED
                assert testing_user['gender'] is not None
                assert testing_user['gender'] == caller.gender
            else:
                assert testing_user.gender is not RESTRICTED 
                assert testing_user.gender is not None
                assert testing_user.gender == caller.gender
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()
            
# Test Case 17: Read other Person’s gender
# on endpoint user() 
# Should pass
def test_case_17_Any_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    target = Person.query.get(5)
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(target,AnyPurpose,"Person","gender")
        except Exception:
            assert False
        # Test user()
        try:
            from project import user
            result = user(5)
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['gender'] is not RESTRICTED
                assert testing_user['gender'] is not None
            else:
                assert testing_user.gender is not RESTRICTED 
                assert testing_user.gender == 'male'
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

