"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user, AnonymousUserMixin
from flask_user import current_user
from dtm import db
from project import *
from instrumentation import Restrict, PrivacyException
from flask_principal import Identity, identity_changed, AnonymousIdentity
from implicits import implicits
from werkzeug.datastructures import MultiDict

RESTRICTED = Restrict()

# This test suite is dedicated for PRIVACY tests

# Test Case 294: Read a Category’s subscribers’s surname as the moderator of the category
# on endpoint view_category() 
# Should fail
def test_case_294_view_category(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test view_category()
        try:
            from project import view_category
            result = view_category(13) 
            assert len(result['category_subscriber_surnames']) == 0 or result['category_subscriber_surnames'][0] == RESTRICTED
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 326: Read a Category’s events’s owner’s surname as non-moderator, as requester
# on endpoint view_category() 
# Should fail
def test_case_326_view_category(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test view_category()
        try:
            from project import view_category
            result = view_category(14)  
            assert len(result['category_event_owner_surnames']) == 0 or (
                result['category_event_owner_surnames'][0] == RESTRICTED and
                result['category_event_owner_surnames'][1] == RESTRICTED and
                result['category_event_owner_surnames'][2] == RESTRICTED and
                result['category_event_owner_surnames'][3] == RESTRICTED and
                result['category_event_owner_surnames'][4] == RESTRICTED and
                result['category_event_owner_surnames'][5] == RESTRICTED and
                result['category_event_owner_surnames'][6] == RESTRICTED)
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 327: Read a Category’s events’s owner’s surname as non-moderator, as stranger
# on endpoint view_category() 
# Should fail
def test_case_327_view_category(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test view_category()
        try:
            from project import view_category
            result = view_category(14)  
            assert len(result['category_event_owner_surnames']) == 0 or (
                result['category_event_owner_surnames'][0] == RESTRICTED and
                result['category_event_owner_surnames'][1] == RESTRICTED and
                result['category_event_owner_surnames'][2] == RESTRICTED and
                result['category_event_owner_surnames'][3] == RESTRICTED and
                result['category_event_owner_surnames'][4] == RESTRICTED and
                result['category_event_owner_surnames'][5] == RESTRICTED and
                result['category_event_owner_surnames'][6] == RESTRICTED)
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()