"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user, AnonymousUserMixin
from flask_user import current_user
from model import *
from project import *
from dto import RESTRICTED
from flask_principal import Identity, identity_changed, AnonymousIdentity
from implicits import implicits
from werkzeug.datastructures import MultiDict

# This test suite is dedicated for PRIVACY tests.

PURPOSES = [
    AnyPurpose,
    FunctionalPurpose,
    MarketingPurpose,
    AnalyticsPurpose,
    CorePurpose,
    RecommendEventsPurpose,
    TargetedMarketingPurpose,
    MassMarketingPurpose,
    InsightsPurpose,
    StatsPurpose
]

def revoke_consent(user,purpose,resource,subresource):
    my_purpose = Purpose.query.filter_by(name=purpose).first()
    consents = Consent.query.filter_by(person_id=user.id, purpose_id=my_purpose.id, classname=resource, propertyname=subresource).all()
    for consent in consents:
        db.session.delete(consent)

def grant_consent(user,purpose,resource,subresource):
    my_purpose = Purpose.query.filter_by(name=purpose).first()
    db.session.add(Consent(classname=resource,propertyname=subresource,user=user,purpose=my_purpose))
    db.session.commit()

def is_response(result):
    return type(result) == Response
    
@implicits("app_with_data")
def login_user(user, app_with_data):
    from flask_login import login_user
    login_user(user)
    identity_changed.send(app_with_data, identity=Identity(current_user.id))

# Test Case 292: Read a Category’s subscribers’s name as the moderator of the category
# on endpoint view_category() 
# Should pass
def test_case_292_view_category(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner,CorePurpose,"Person","name")
        except Exception:
            assert False
        # Test view_category()
        try:
            from project import view_category
            result = view_category(13)  
            testing_category = result['category']
            assert testing_category.subscribers is not RESTRICTED
            assert len(testing_category.subscribers) == 1
            assert set([subscriber.name for subscriber in testing_category.subscribers]) == set(['p0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 294: Read a Category’s subscribers’s surname as the moderator of the category
# on endpoint view_category() 
# Should pass
def test_case_294_view_category(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner,CorePurpose,"Person","surname")
        except Exception:
            assert False
        # Test view_category()
        try:
            from project import view_category
            result = view_category(13) 
            testing_category = result['category']
            assert testing_category.subscribers is not RESTRICTED
            assert len(testing_category.subscribers) == 1
            assert set([subscriber.surname for subscriber in testing_category.subscribers]) == set(['p0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 316: Read a Category’s events’s owner’s name as the moderator of the category
# on endpoint view_category() 
# Should pass
def test_case_316_view_category(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner3 = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","name")
            grant_consent(owner1,CorePurpose,"Person","name")
            grant_consent(owner2,CorePurpose,"Person","name")
            grant_consent(owner3,CorePurpose,"Person","name")
        except Exception:
            assert False
        # Test view_category()
        try:
            from project import view_category
            result = view_category(13)  
            testing_category = result['category']
            assert testing_category.events is not RESTRICTED
            assert len(testing_category.events) == 7
            assert set([event.owner.name for event in testing_category.events]) == set(['FREEUSER0', 'MODERATOR0', 'ADMIN0', 'p0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 317: Read a Category’s events’s owner’s name as non-moderator, as owner
# on endpoint view_category() 
# Should pass
def test_case_317_view_category(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner3 = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","name")
            grant_consent(owner1,CorePurpose,"Person","name")
            grant_consent(owner2,CorePurpose,"Person","name")
            grant_consent(owner3,CorePurpose,"Person","name")
        except Exception:
            assert False
        # Test view_category()
        try:
            from project import view_category
            result = view_category(14)  
            testing_category = result['category']
            assert testing_category.events is not RESTRICTED
            assert len(testing_category.events) == 7
            assert set([event.owner.name for event in testing_category.events]) == set(['FREEUSER0', 'MODERATOR0', 'ADMIN0', 'p0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 318: Read a Category’s events’s owner’s name as non-moderator, as manager
# on endpoint view_category() 
# Should pass
def test_case_318_view_category(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner3 = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","name")
            grant_consent(owner1,CorePurpose,"Person","name")
            grant_consent(owner2,CorePurpose,"Person","name")
            grant_consent(owner3,CorePurpose,"Person","name")
        except Exception:
            assert False
        # Test view_category()
        try:
            from project import view_category
            result = view_category(14)  
            testing_category = result['category']
            assert testing_category.events is not RESTRICTED
            assert len(testing_category.events) == 7
            assert set([event.owner.name for event in testing_category.events]) == set(['FREEUSER0', 'MODERATOR0', 'ADMIN0', 'p0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 319: Read a Category’s events’s owner’s name as non-moderator, as attendant
# on endpoint view_category() 
# Should pass
def test_case_319_view_category(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner3 = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","name")
            grant_consent(owner1,CorePurpose,"Person","name")
            grant_consent(owner2,CorePurpose,"Person","name")
            grant_consent(owner3,CorePurpose,"Person","name")
        except Exception:
            assert False
        # Test view_category()
        try:
            from project import view_category
            result = view_category(14) 
            testing_category = result['category']
            assert testing_category.events is not RESTRICTED
            assert len(testing_category.events) == 7
            assert set([event.owner.name for event in testing_category.events]) == set(['FREEUSER0', 'MODERATOR0', 'ADMIN0', 'p0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 320: Read a Category’s events’s owner’s name as non-moderator, as requester
# on endpoint view_category() 
# Should pass
def test_case_320_view_category(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner3 = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","name")
            grant_consent(owner1,CorePurpose,"Person","name")
            grant_consent(owner2,CorePurpose,"Person","name")
            grant_consent(owner3,CorePurpose,"Person","name")
        except Exception:
            assert False
        # Test view_category()
        try:
            from project import view_category
            result = view_category(14)  
            testing_category = result['category']
            assert testing_category.events is not RESTRICTED
            assert len(testing_category.events) == 7
            assert set([event.owner.name for event in testing_category.events]) == set(['FREEUSER0', 'MODERATOR0', 'ADMIN0', 'p0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 321: Read a Category’s events’s owner’s name as non-moderator, as stranger
# on endpoint view_category() 
# Should pass
def test_case_321_view_category(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner3 = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","name")
            grant_consent(owner1,CorePurpose,"Person","name")
            grant_consent(owner2,CorePurpose,"Person","name")
            grant_consent(owner3,CorePurpose,"Person","name")
        except Exception:
            assert False
        # Test view_category()
        try:
            from project import view_category
            result = view_category(14) 
            testing_category = result['category']
            assert testing_category.events is not RESTRICTED
            assert len(testing_category.events) == 7
            assert set([event.owner.name for event in testing_category.events]) == set(['FREEUSER0', 'MODERATOR0', 'ADMIN0', 'p0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 322: Read a Category’s events’s owner’s surname as the moderator of the category
# on endpoint view_category() 
# Should pass
def test_case_322_view_category(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner3 = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","surname")
            grant_consent(owner1,CorePurpose,"Person","surname")
            grant_consent(owner2,CorePurpose,"Person","surname")
            grant_consent(owner3,CorePurpose,"Person","surname")
        except Exception:
            assert False
        # Test view_category()
        try:
            from project import view_category
            result = view_category(13)  
            testing_category = result['category']
            assert testing_category.events is not RESTRICTED
            assert len(testing_category.events) == 7
            assert set([event.owner.surname for event in testing_category.events]) == set(['FREEUSER0', 'MODERATOR0', 'ADMIN0', 'p0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 323: Read a Category’s events’s owner’s surname as non-moderator, as owner
# on endpoint view_category() 
# Should pass
def test_case_323_view_category(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner3 = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","surname")
            grant_consent(owner1,CorePurpose,"Person","surname")
            grant_consent(owner2,CorePurpose,"Person","surname")
            grant_consent(owner3,CorePurpose,"Person","surname")
        except Exception:
            assert False
        # Test view_category()
        try:
            from project import view_category
            result = view_category(14) 
            testing_category = result['category']
            assert testing_category.events is not RESTRICTED
            assert len(testing_category.events) == 7
            assert set([event.owner.surname for event in testing_category.events]) == set(['FREEUSER0', 'MODERATOR0', 'ADMIN0', 'p0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 324: Read a Category’s events’s owner’s surname as non-moderator, as manager
# on endpoint view_category() 
# Should pass
def test_case_324_view_category(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner3 = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","surname")
            grant_consent(owner1,CorePurpose,"Person","surname")
            grant_consent(owner2,CorePurpose,"Person","surname")
            grant_consent(owner3,CorePurpose,"Person","surname")
        except Exception:
            assert False
        # Test view_category()
        try:
            from project import view_category
            result = view_category(14)  
            testing_category = result['category']
            assert testing_category.events is not RESTRICTED
            assert len(testing_category.events) == 7
            assert set([event.owner.surname for event in testing_category.events]) == set(['FREEUSER0', 'MODERATOR0', 'ADMIN0', 'p0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 325: Read a Category’s events’s owner’s surname as non-moderator, as attendant
# on endpoint view_category() 
# Should pass
def test_case_325_view_category(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner3 = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","surname")
            grant_consent(owner1,CorePurpose,"Person","surname")
            grant_consent(owner2,CorePurpose,"Person","surname")
            grant_consent(owner3,CorePurpose,"Person","surname")
        except Exception:
            assert False
        # Test view_category()
        try:
            from project import view_category
            result = view_category(14)  
            testing_category = result['category']
            assert testing_category.events is not RESTRICTED
            assert len(testing_category.events) == 7
            assert set([event.owner.surname for event in testing_category.events]) == set(['FREEUSER0', 'MODERATOR0', 'ADMIN0', 'p0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 326: Read a Category’s events’s owner’s surname as non-moderator, as requester
# on endpoint view_category() 
# Should pass
def test_case_326_view_category(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner3 = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","surname")
            grant_consent(owner1,CorePurpose,"Person","surname")
            grant_consent(owner2,CorePurpose,"Person","surname")
            grant_consent(owner3,CorePurpose,"Person","surname")
        except Exception:
            assert False
        # Test view_category()
        try:
            from project import view_category
            result = view_category(14)  
            testing_category = result['category']
            assert testing_category.events is not RESTRICTED
            assert len(testing_category.events) == 7
            assert set([event.owner.surname for event in testing_category.events]) == set(['FREEUSER0', 'MODERATOR0', 'ADMIN0', 'p0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 327: Read a Category’s events’s owner’s surname as non-moderator, as stranger
# on endpoint view_category() 
# Should pass
def test_case_327_view_category(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner3 = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","surname")
            grant_consent(owner1,CorePurpose,"Person","surname")
            grant_consent(owner2,CorePurpose,"Person","surname")
            grant_consent(owner3,CorePurpose,"Person","surname")
        except Exception:
            assert False
        # Test view_category()
        try:
            from project import view_category
            result = view_category(14)  
            testing_category = result['category']
            assert testing_category.events is not RESTRICTED
            assert len(testing_category.events) == 7
            assert set([event.owner.surname for event in testing_category.events]) == set(['FREEUSER0', 'MODERATOR0', 'ADMIN0', 'p0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

