"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user, AnonymousUserMixin
from flask_user import current_user
from model import *
from project import *
from dto import RESTRICTED
from flask_principal import Identity, identity_changed, AnonymousIdentity
from implicits import implicits

# This test suite is dedicated for PRIVACY tests.

PURPOSES = [
    AnyPurpose,
    FunctionalPurpose,
    MarketingPurpose,
    AnalyticsPurpose,
    CorePurpose,
    RecommendEventsPurpose,
    TargetedMarketingPurpose,
    MassMarketingPurpose,
    InsightsPurpose,
    StatsPurpose
]

def revoke_consent(user,purpose,resource,subresource):
    my_purpose = Purpose.query.filter_by(name=purpose).first()
    consents = Consent.query.filter_by(person_id=user.id, purpose_id=my_purpose.id, classname=resource, propertyname=subresource).all()
    for consent in consents:
        db.session.delete(consent)

def grant_consent(user,purpose,resource,subresource):
    my_purpose = Purpose.query.filter_by(name=purpose).first()
    db.session.add(Consent(classname=resource,propertyname=subresource,user=user,purpose=my_purpose))
    db.session.commit()

def is_response(result):
    return type(result) == Response
    
@implicits("app_with_data")
def login_user(user, app_with_data):
    from flask_login import login_user
    login_user(user)
    identity_changed.send(app_with_data, identity=Identity(current_user.id))

# Test Case 8: Read other Person’s name
# on endpoint users() 
# Should pass
def test_case_8_users(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    target = Person.query.filter(Person.testid == 'p1').one() 
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(target,CorePurpose,"Person","name")
        except Exception:
            assert False
        # Test users()
        try:
            from project import users
            result = users()
            users = result['users']
            testing_user = None
            for user in users:
                if user.testid == target.testid:
                    testing_user = user
                    break
            if type(testing_user) is dict:
                assert testing_user['name'] is not RESTRICTED
                assert testing_user['name'] is not None
                assert testing_user['name'] == 'p1'
            else:
                assert testing_user.name is not RESTRICTED 
                assert testing_user.name is not None
                assert testing_user.name == 'p1'
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 16: Read one’s own gender
# on endpoint user() 
# Should pass
def test_case_16_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","gender")
        except Exception:
            assert False
        # Test user()
        try:
            from project import user
            result = user(4)
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['gender'] is not RESTRICTED
                assert testing_user['gender'] is not None
                assert testing_user['gender'] == caller.gender
            else:
                assert testing_user.gender is not RESTRICTED 
                assert testing_user.gender is not None
                assert testing_user.gender == caller.gender
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 18: Read one’s own email
# on endpoint user() 
# Should pass
def test_case_18_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","email")
        except Exception:
            assert False
        # Test user()
        try:
            from project import user
            result = user(4)
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['email'] is not RESTRICTED
                assert testing_user['email'] is not None
                assert testing_user['email'] == caller.email
            else:
                assert testing_user.email is not RESTRICTED 
                assert testing_user.email is not None
                assert testing_user.email == caller.email
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

