"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user, AnonymousUserMixin
from flask_user import current_user
from model import db
from project import *
from dto import RESTRICTED
from flask_principal import Identity, identity_changed, AnonymousIdentity
from implicits import implicits
from werkzeug.datastructures import MultiDict

# This test suite is dedicated for PRIVACY tests.

def is_response(result):
    return type(result) == Response
    
@implicits("app_with_data")
def login_user(user, app_with_data):
    from flask_login import login_user
    login_user(user)
    identity_changed.send(app_with_data, identity=Identity(current_user.id))

# Test Case 260: Read a Category’s moderators’s name as the non-moderator of the category
# on endpoint edit_category() 
# Should fail
def test_case_260_edit_category(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test edit_category()
        try:
            from project import edit_category
            result = edit_category(14) 
            assert result is not None
            testing_category = result['category']
            assert testing_category is not None
            assert testing_category.moderators is not RESTRICTED
            assert len(testing_category.moderators) == 1
            assert testing_category.moderators[0].name is RESTRICTED
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 262: Read a Category’s moderators’s surname as the non-moderator of the category
# on endpoint edit_category() 
# Should fail
def test_case_262_edit_category(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test edit_category()
        try:
            from project import edit_category
            result = edit_category(14) 
            assert result is not None
            testing_category = result['category']
            assert testing_category is not None
            assert testing_category.moderators is not RESTRICTED
            assert len(testing_category.moderators) == 1
            assert testing_category.moderators[0].surname is RESTRICTED
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 259: Read a Category’s moderators’s name as the moderator of the category
# on endpoint edit_category() 
# Should fail
def test_case_259_edit_category(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test edit_category()
        try:
            from project import edit_category
            result = edit_category(13)
            assert result is not None
            testing_category = result['category']
            assert testing_category is not None
            assert testing_category.moderators is not RESTRICTED
            assert len(testing_category.moderators) == 1
            assert testing_category.moderators[0].name is RESTRICTED
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 261: Read a Category’s moderators’s surname as the moderator of the category
# on endpoint edit_category() 
# Should fail
def test_case_261_edit_category(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test edit_category()
        try:
            from project import edit_category
            result = edit_category(13)
            assert result is not None
            testing_category = result['category']
            assert testing_category is not None
            assert testing_category.moderators is not RESTRICTED
            assert len(testing_category.moderators) == 1
            assert testing_category.moderators[0].surname is RESTRICTED
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 265: Read a Category’s candidates’s name as the moderator of the category
# on endpoint edit_category() 
# Should fail
def test_case_265_edit_category(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test edit_category()
        try:
            from project import edit_category
            result = edit_category(13)
            assert result is not None
            testing_candidates = result['candidates']
            assert testing_candidates is RESTRICTED or len(testing_candidates) == 0
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 273: Send mass ads as a moderator of the category
# on endpoint send_mass_advertisement() 
# Should fail
def test_case_273_send_mass_advertisement(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test send_mass_advertisement()
        try:
            from project import send_mass_advertisement
            send_mass_advertisement(13)  
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 275: Analyze an event as an owner
# on endpoint analyze() 
# Should fail
def test_case_275_analyze(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test analyze()
        try:
            from project import analyze
            result = analyze(8)  
            assert result['male'] is RESTRICTED or result['male'] == 0
            assert result['female'] is RESTRICTED or result['female'] == 0
            db.session.rollback()
        except PrivacyException:
            db.session.rollback()
            assert True
        finally:
            db.session.rollback()

# Test Case 276: Analyze an event as a manager
# on endpoint analyze() 
# Should fail
def test_case_276_analyze(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test analyze()
        try:
            from project import analyze
            result = analyze(9)  
            assert result['male'] is RESTRICTED or result['male'] == 0
            assert result['female'] is RESTRICTED or result['female'] == 0
            db.session.rollback()
        except PrivacyException:
            db.session.rollback()
            assert True
        finally:
            db.session.rollback()

# Test Case 277: Analyze an event as an attendant
# on endpoint analyze() 
# Should fail
def test_case_277_analyze(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test analyze()
        try:
            from project import analyze
            result = analyze(10)  
            assert result['male'] is RESTRICTED or result['male'] == 0
            assert result['female'] is RESTRICTED or result['female'] == 0
            db.session.rollback()
        except PrivacyException:
            db.session.rollback()
            assert True
        finally:
            db.session.rollback()

# Test Case 278: Analyze an event as a requester
# on endpoint analyze() 
# Should fail
def test_case_278_analyze(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test analyze()
        try:
            from project import analyze
            result = analyze(11)  
            assert result['male'] is RESTRICTED or result['male'] == 0
            assert result['female'] is RESTRICTED or result['female'] == 0
            db.session.rollback()
        except PrivacyException:
            db.session.rollback()
            assert True
        finally:
            db.session.rollback()

# Test Case 279: Analyze an event as someone else
# on endpoint analyze() 
# Should fail
def test_case_279_analyze(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test analyze()
        try:
            from project import analyze
            result = analyze(12)  
            assert result['male'] is RESTRICTED or result['male'] == 0
            assert result['female'] is RESTRICTED or result['female'] == 0
            db.session.rollback()
        except PrivacyException:
            db.session.rollback()
            assert True
        finally:
            db.session.rollback()
