"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user, AnonymousUserMixin
from flask_user import current_user
from model import *
from project import *
from dto import RESTRICTED
from flask_principal import Identity, identity_changed, AnonymousIdentity
from implicits import implicits
from werkzeug.datastructures import MultiDict

# This test suite is dedicated for PRIVACY tests.

PURPOSES = [
    AnyPurpose,
    FunctionalPurpose,
    MarketingPurpose,
    AnalyticsPurpose,
    CorePurpose,
    RecommendEventsPurpose,
    TargetedMarketingPurpose,
    MassMarketingPurpose
]

def revoke_consent(user,purpose,resource,subresource):
    my_purpose = Purpose.query.filter_by(name=purpose).first()
    consents = Consent.query.filter_by(person_id=user.id, purpose_id=my_purpose.id, classname=resource, propertyname=subresource).all()
    for consent in consents:
        db.session.delete(consent)

def grant_consent(user,purpose,resource,subresource):
    my_purpose = Purpose.query.filter_by(name=purpose).first()
    db.session.add(Consent(classname=resource,propertyname=subresource,user=user,purpose=my_purpose))
    db.session.commit()

def is_response(result):
    return type(result) == Response
    
@implicits("app_with_data")
def login_user(user, app_with_data):
    from flask_login import login_user
    login_user(user)
    identity_changed.send(app_with_data, identity=Identity(current_user.id))

# Test Case 166: Read an Event’s attendants’ name field that one owns
# on endpoint manage_event() 
# Should pass
def test_case_166_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","name")
        except Exception:
            assert False
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(9)
            testing_event = result['event']
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 1
            assert set([attendant.name for attendant in testing_event.attendants]) == set(['ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 167: Read an Event’s attendants’ name field that one manages
# on endpoint manage_event() 
# Should pass
def test_case_167_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner3 = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","name")
            grant_consent(owner1,CorePurpose,"Person","name")
            grant_consent(owner2,CorePurpose,"Person","name")
            grant_consent(owner3,CorePurpose,"Person","name")
        except Exception:
            assert False
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(10)
            testing_event = result['event']
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 4
            assert set([attendant.name for attendant in testing_event.attendants]) == set(['p0', 'FREEUSER0', 'MODERATOR0', 'ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 168: Read an Event’s attendants’ name field that one attends
# on endpoint manage_event() 
# Should pass
def test_case_168_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner3 = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","name")
            grant_consent(owner1,CorePurpose,"Person","name")
            grant_consent(owner2,CorePurpose,"Person","name")
            grant_consent(owner3,CorePurpose,"Person","name")
        except Exception:
            assert False
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(11)
            testing_event = result['event']
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 4
            assert set([attendant.name for attendant in testing_event.attendants]) == set(['p0', 'FREEUSER0', 'MODERATOR0', 'ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 169: Read an Event’s attendants’ name field that one requests
# on endpoint manage_event() 
# Should pass
def test_case_169_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'p0').one()
    owner2 = Person.query.filter(Person.testid == 'p2').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner1,CorePurpose,"Person","name")
            grant_consent(owner2,CorePurpose,"Person","name")
        except Exception:
            assert False
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(12)
            testing_event = result['event']
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 2
            assert set([attendant.name for attendant in testing_event.attendants]) == set(['p0', 'p2'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 170: Read an Event’s attendants’ name one doesn’t own, manage, attend, or request
# on endpoint manage_event() 
# Should pass
def test_case_170_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'p0').one()
    owner2 = Person.query.filter(Person.testid == 'p3').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner1,CorePurpose,"Person","name")
            grant_consent(owner2,CorePurpose,"Person","name")
        except Exception:
            assert False
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(13)
            testing_event = result['event']
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 2
            assert set([attendant.name for attendant in testing_event.attendants]) == set(['p0', 'p3'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 171: Read an Event’s attendants’ surname field that one owns
# on endpoint manage_event() 
# Should pass
def test_case_171_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","surname")
        except Exception:
            assert False
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(9)
            testing_event = result['event']
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 1
            assert set([attendant.surname for attendant in testing_event.attendants]) == set(['ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 172: Read an Event’s attendants’ surname field that one manages
# on endpoint manage_event() 
# Should pass
def test_case_172_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner3 = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","surname")
            grant_consent(owner1,CorePurpose,"Person","surname")
            grant_consent(owner2,CorePurpose,"Person","surname")
            grant_consent(owner3,CorePurpose,"Person","surname")
        except Exception:
            assert False
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(10)
            testing_event = result['event']
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 4
            assert set([attendant.surname for attendant in testing_event.attendants]) == set(['p0', 'FREEUSER0', 'MODERATOR0', 'ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 173: Read an Event’s attendants’ surname field that one attends
# on endpoint manage_event() 
# Should pass
def test_case_173_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner3 = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","surname")
            grant_consent(owner1,CorePurpose,"Person","surname")
            grant_consent(owner2,CorePurpose,"Person","surname")
            grant_consent(owner3,CorePurpose,"Person","surname")
        except Exception:
            assert False
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(11)
            testing_event = result['event']
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 4
            assert set([attendant.surname for attendant in testing_event.attendants]) == set(['p0', 'FREEUSER0', 'MODERATOR0', 'ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 174: Read an Event’s attendants’ surname field that one requests
# on endpoint manage_event() 
# Should pass
def test_case_174_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'p0').one()
    owner2 = Person.query.filter(Person.testid == 'p2').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner1,CorePurpose,"Person","surname")
            grant_consent(owner2,CorePurpose,"Person","surname")
        except Exception:
            assert False
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(12)
            testing_event = result['event']
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 2
            assert set([attendant.surname for attendant in testing_event.attendants]) == set(['p0', 'p2'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 175: Read an Event’s attendants’ surname one doesn’t own, manage, attend, or request
# on endpoint manage_event() 
# Should pass
def test_case_175_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'p0').one()
    owner2 = Person.query.filter(Person.testid == 'p3').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner1,CorePurpose,"Person","surname")
            grant_consent(owner2,CorePurpose,"Person","surname")
        except Exception:
            assert False
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(13)
            testing_event = result['event']
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 2
            assert set([attendant.surname for attendant in testing_event.attendants]) == set(['p0', 'p3'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 181: Read an Event’s managedBy’ name field that one owns
# on endpoint manage_event() 
# Should pass
def test_case_181_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","name")
        except Exception:
            assert False
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(9)
            testing_event = result['event']
            assert testing_event.managedBy is not RESTRICTED
            assert len(testing_event.managedBy) == 1
            assert set([manager.name for manager in testing_event.managedBy]) == set(['ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 182: Read an Event’s managedBy’ name field that one manages
# on endpoint manage_event() 
# Should pass
def test_case_182_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner3 = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","name")
            grant_consent(owner1,CorePurpose,"Person","name")
            grant_consent(owner2,CorePurpose,"Person","name")
            grant_consent(owner3,CorePurpose,"Person","name")
        except Exception:
            assert False
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(10)
            testing_event = result['event']
            assert testing_event.managedBy is not RESTRICTED
            assert len(testing_event.managedBy) == 4
            assert set([manager.name for manager in testing_event.managedBy]) == set(['p0', 'FREEUSER0', 'MODERATOR0', 'ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 183: Read an Event’s managedBy’ name field that one attends
# on endpoint manage_event() 
# Should pass
def test_case_183_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner,CorePurpose,"Person","name")
        except Exception:
            assert False
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(11)
            testing_event = result['event']
            assert testing_event.managedBy is not RESTRICTED
            assert len(testing_event.managedBy) == 1
            assert set([manager.name for manager in testing_event.managedBy]) == set(['p0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 184: Read an Event’s managedBy’ name field that one requests
# on endpoint manage_event() 
# Should pass
def test_case_184_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner,CorePurpose,"Person","name")
        except Exception:
            assert False
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(12)
            testing_event = result['event']
            assert testing_event.managedBy is not RESTRICTED
            assert len(testing_event.managedBy) == 1
            assert set([manager.name for manager in testing_event.managedBy]) == set(['p0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 185: Read an Event’s managedBy’ name one doesn’t own, manage, attend, or request
# on endpoint manage_event() 
# Should pass
def test_case_185_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner,CorePurpose,"Person","name")
        except Exception:
            assert False
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(13)
            testing_event = result['event']
            assert testing_event.managedBy is not RESTRICTED
            assert len(testing_event.managedBy) == 1
            assert set([manager.name for manager in testing_event.managedBy]) == set(['p0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 186: Read an Event’s managedBy’ surname field that one owns
# on endpoint manage_event() 
# Should pass
def test_case_186_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","surname")
        except Exception:
            assert False
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(9)
            testing_event = result['event']
            assert testing_event.managedBy is not RESTRICTED
            assert len(testing_event.managedBy) == 1
            assert set([manager.surname for manager in testing_event.managedBy]) == set(['ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 187: Read an Event’s managedBy’ surname field that one manages
# on endpoint manage_event() 
# Should pass
def test_case_187_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner3 = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","surname")
            grant_consent(owner1,CorePurpose,"Person","surname")
            grant_consent(owner2,CorePurpose,"Person","surname")
            grant_consent(owner3,CorePurpose,"Person","surname")
        except Exception:
            assert False
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(10)
            testing_event = result['event']
            assert testing_event.managedBy is not RESTRICTED
            assert len(testing_event.managedBy) == 4
            assert set([manager.surname for manager in testing_event.managedBy]) == set(['p0', 'FREEUSER0', 'MODERATOR0', 'ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 188: Read an Event’s managedBy’ surname field that one attends
# on endpoint manage_event() 
# Should pass
def test_case_188_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner,CorePurpose,"Person","surname")
        except Exception:
            assert False
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(11)
            testing_event = result['event']
            assert testing_event.managedBy is not RESTRICTED
            assert len(testing_event.managedBy) == 1
            assert set([manager.surname for manager in testing_event.managedBy]) == set(['p0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 189: Read an Event’s managedBy’ surname field that one requests
# on endpoint manage_event() 
# Should pass
def test_case_189_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner,CorePurpose,"Person","surname")
        except Exception:
            assert False
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(12)
            testing_event = result['event']
            assert testing_event.managedBy is not RESTRICTED
            assert len(testing_event.managedBy) == 1
            assert set([manager.surname for manager in testing_event.managedBy]) == set(['p0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 190: Read an Event’s managedBy’ surname one doesn’t own, manage, attend, or request
# on endpoint manage_event() 
# Should pass
def test_case_190_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner,CorePurpose,"Person","surname")
        except Exception:
            assert False
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(13)
            testing_event = result['event']
            assert testing_event.managedBy is not RESTRICTED
            assert len(testing_event.managedBy) == 1
            assert set([manager.surname for manager in testing_event.managedBy]) == set(['p0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 196: Read an Event’s requesters’ name field that one owns
# on endpoint manage_event() 
# Should pass
def test_case_196_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner,CorePurpose,"Person","name")
        except Exception:
            assert False
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(9)
            testing_event = result['event']
            assert testing_event.requesters is not RESTRICTED
            assert len(testing_event.requesters) == 1
            assert set([requester.name for requester in testing_event.requesters]) == set(['p1'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 197: Read an Event’s requesters’ name field that one manages
# on endpoint manage_event() 
# Should pass
def test_case_197_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner,CorePurpose,"Person","name")
        except Exception:
            assert False
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(10)
            testing_event = result['event']
            assert testing_event.requesters is not RESTRICTED
            assert len(testing_event.requesters) == 1
            assert set([requester.name for requester in testing_event.requesters]) == set(['p1'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 201: Read an Event’s requesters’ surname field that one owns
# on endpoint manage_event() 
# Should pass
def test_case_201_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner,CorePurpose,"Person","surname")
        except Exception:
            assert False
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(9)
            testing_event = result['event']
            assert testing_event.requesters is not RESTRICTED
            assert len(testing_event.requesters) == 1
            assert set([requester.surname for requester in testing_event.requesters]) == set(['p1'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 202: Read an Event’s requesters’ surname field that one manages
# on endpoint manage_event() 
# Should pass
def test_case_202_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner,CorePurpose,"Person","surname")
        except Exception:
            assert False
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(10)
            testing_event = result['event']
            assert testing_event.requesters is not RESTRICTED
            assert len(testing_event.requesters) == 1
            assert set([requester.surname for requester in testing_event.requesters]) == set(['p1'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

