"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user, AnonymousUserMixin
from flask_user import current_user
from model import db
from project import *
from dto import RESTRICTED
from flask_principal import Identity, identity_changed, AnonymousIdentity
from implicits import implicits
from werkzeug.datastructures import MultiDict

# This test suite is dedicated for users with ADMIN role
# Tests that are applicable to ADMIN role.

def is_response(result):
    return type(result) == Response
    
@implicits("app_with_data")
def login_user(user, app_with_data):
    from flask_login import login_user
    login_user(user)
    identity_changed.send(app_with_data, identity=Identity(current_user.id))

# Test Case 169: Read an Event’s attendants’ name field that one requests
# on endpoint manage_event() 
# Should fail
def test_case_169_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(12)
            testing_event = result['event']
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 2
            assert testing_event.attendants[0].name is RESTRICTED
            assert testing_event.attendants[1].name is RESTRICTED
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 173: Read an Event’s attendants’ surname field that one attends
# on endpoint manage_event() 
# Should fail
def test_case_173_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(11)
            testing_event = result['event']
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 4
            assert testing_event.attendants[0].surname is RESTRICTED
            assert testing_event.attendants[1].surname is RESTRICTED
            assert testing_event.attendants[2].surname is RESTRICTED
            assert testing_event.attendants[3].surname is RESTRICTED
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 187: Read an Event’s managedBy’ surname field that one manages
# on endpoint manage_event() 
# Should fail
def test_case_187_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(10)
            testing_event = result['event']
            assert testing_event.managedBy is not RESTRICTED
            assert len(testing_event.managedBy) == 4
            assert testing_event.managedBy[0].surname is RESTRICTED
            assert testing_event.managedBy[1].surname is RESTRICTED
            assert testing_event.managedBy[2].surname is RESTRICTED
            assert testing_event.managedBy[3].surname is RESTRICTED
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

