"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user, AnonymousUserMixin
from flask_user import current_user
from model import *
from project import *
from dto import RESTRICTED
from flask_principal import Identity, identity_changed, AnonymousIdentity
from implicits import implicits
from werkzeug.datastructures import MultiDict

# This test suite is dedicated for PRIVACY tests.

PURPOSES = [
    AnyPurpose,
    FunctionalPurpose,
    MarketingPurpose,
    AnalyticsPurpose,
    CorePurpose,
    RecommendEventsPurpose,
    TargetedMarketingPurpose,
    MassMarketingPurpose
]

def revoke_consent(user,purpose,resource,subresource):
    my_purpose = Purpose.query.filter_by(name=purpose).first()
    consents = Consent.query.filter_by(person_id=user.id, purpose_id=my_purpose.id, classname=resource, propertyname=subresource).all()
    for consent in consents:
        db.session.delete(consent)

def grant_consent(user,purpose,resource,subresource):
    my_purpose = Purpose.query.filter_by(name=purpose).first()
    db.session.add(Consent(classname=resource,propertyname=subresource,user=user,purpose=my_purpose))
    db.session.commit()

def is_response(result):
    return type(result) == Response
    
@implicits("app_with_data")
def login_user(user, app_with_data):
    from flask_login import login_user
    login_user(user)
    identity_changed.send(app_with_data, identity=Identity(current_user.id))

# Test Case 166: Read an Event’s attendants’ name field that one owns
# on endpoint manage_event() 
# Should pass
def test_case_166_FUNCTIONAL_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,FunctionalPurpose,"Person","name")
        except Exception:
            assert False
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(9)
            testing_event = result['event']
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 1
            assert set([attendant.name for attendant in testing_event.attendants]) == set(['ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 168: Read an Event’s attendants’ name field that one attends
# on endpoint manage_event() 
# Should pass
def test_case_168_FUNCTIONAL_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner3 = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,FunctionalPurpose,"Person","name")
            grant_consent(owner1,FunctionalPurpose,"Person","name")
            grant_consent(owner2,FunctionalPurpose,"Person","name")
            grant_consent(owner3,FunctionalPurpose,"Person","name")
        except Exception:
            assert False
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(11)
            testing_event = result['event']
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 4
            assert set([attendant.name for attendant in testing_event.attendants]) == set(['p0', 'FREEUSER0', 'MODERATOR0', 'ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 190: Read an Event’s managedBy’ surname one doesn’t own, manage, attend, or request
# on endpoint manage_event() 
# Should pass
def test_case_190_ANY_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner,AnyPurpose,"Person","surname")
        except Exception:
            assert False
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(13)
            testing_event = result['event']
            assert testing_event.managedBy is not RESTRICTED
            assert len(testing_event.managedBy) == 1
            assert set([manager.surname for manager in testing_event.managedBy]) == set(['p0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

