"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user, AnonymousUserMixin
from flask_user import current_user
from model import *
from project import *
from dto import RESTRICTED
from flask_principal import Identity, identity_changed, AnonymousIdentity
from implicits import implicits

# This test suite is dedicated for PRIVACY tests.

PURPOSES = [
    AnyPurpose,
    FunctionalPurpose,
    MarketingPurpose,
    AnalyticsPurpose,
    CorePurpose,
    RecommendEventsPurpose,
    TargetedMarketingPurpose,
    MassMarketingPurpose
]

def revoke_consent(user,purpose,resource,subresource):
    my_purpose = Purpose.query.filter_by(name=purpose).first()
    consents = Consent.query.filter_by(person_id=user.id, purpose_id=my_purpose.id, classname=resource, propertyname=subresource).all()
    for consent in consents:
        db.session.delete(consent)

def grant_consent(user,purpose,resource,subresource):
    my_purpose = Purpose.query.filter_by(name=purpose).first()
    db.session.add(Consent(classname=resource,propertyname=subresource,user=user,purpose=my_purpose))
    db.session.commit()

def is_response(result):
    return type(result) == Response
    
@implicits("app_with_data")
def login_user(user, app_with_data):
    from flask_login import login_user
    login_user(user)
    identity_changed.send(app_with_data, identity=Identity(current_user.id))

# Test Case 1: Read one’s own name
# on endpoint main() 
# Should pass
def test_case_1_Functional_main(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,FunctionalPurpose,"Person","name")
        except Exception:
            assert False
        # Test main()
        try:
            from project import main
            result = main()
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['name'] is not RESTRICTED
                assert testing_user['name'] is not None
                assert testing_user['name'] == caller.name
            else:
                assert testing_user.name is not RESTRICTED
                assert testing_user.name is not None
                assert testing_user.name == caller.name 
        except SecurityException:
            assert False
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 1: Read one’s own name
# on endpoint main() 
# Should pass
def test_case_1_Any_main(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,AnyPurpose,"Person","name")
        except Exception:
            assert False
        # Test main()
        try:
            from project import main
            result = main()
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['name'] is not RESTRICTED
                assert testing_user['name'] is not None
                assert testing_user['name'] == caller.name
            else:
                assert testing_user.name is not RESTRICTED
                assert testing_user.name is not None
                assert testing_user.name == caller.name 
        except SecurityException:
            assert False
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 2: Read one’s own surname
# on endpoint main() 
# Should pass
def test_case_2_Functional_main(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,FunctionalPurpose,"Person","surname")
        except Exception:
            assert False
        # Test main()
        try:
            from project import main
            result = main()
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['surname'] is not RESTRICTED
                assert testing_user['surname'] is not None
                assert testing_user['surname'] == caller.surname
            else:
                assert testing_user.surname is not RESTRICTED
                assert testing_user.surname is not None
                assert testing_user.surname == caller.surname
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 2: Read one’s own surname
# on endpoint main() 
# Should pass
def test_case_2_Any_main(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,AnyPurpose,"Person","surname")
        except Exception:
            assert False
        # Test main()
        try:
            from project import main
            result = main()
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['surname'] is not RESTRICTED
                assert testing_user['surname'] is not None
                assert testing_user['surname'] == caller.surname
            else:
                assert testing_user.surname is not RESTRICTED
                assert testing_user.surname is not None
                assert testing_user.surname == caller.surname
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 6: Read one’s own name
# on endpoint users() 
# Should pass
def test_case_6_Functional_users(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,FunctionalPurpose,"Person","name")
        except Exception:
            assert False
        # Test users()
        try:
            from project import users
            result = users()
            users = result['users']
            testing_user = None
            for user in users:
                if user.testid == 'ADMIN0':
                    testing_user = user
                    break
            if type(testing_user) is dict:
                assert testing_user['name'] is not RESTRICTED
                assert testing_user['name'] is not None
                assert testing_user['name'] == caller.name
            else:
                assert testing_user.name is not RESTRICTED 
                assert testing_user.name is not None
                assert testing_user.name == caller.name
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

def test_case_6_Any_users(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,AnyPurpose,"Person","name")
        except Exception:
            assert False
        # Test users()
        try:
            from project import users
            result = users()
            users = result['users']
            testing_user = None
            for user in users:
                if user.testid == 'ADMIN0':
                    testing_user = user
                    break
            if type(testing_user) is dict:
                assert testing_user['name'] is not RESTRICTED
                assert testing_user['name'] is not None
                assert testing_user['name'] == caller.name
            else:
                assert testing_user.name is not RESTRICTED 
                assert testing_user.name is not None
                assert testing_user.name == caller.name
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 7: Read one’s own surname
# on endpoint users() 
# Should pass
def test_case_7_Functional_users(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,FunctionalPurpose,"Person","surname")
        except Exception:
            assert False
        # Test users()
        try:
            from project import users
            result = users()
            users = result['users']
            testing_user = None
            for user in users:
                if user.testid == 'ADMIN0':
                    testing_user = user
                    break
            if type(testing_user) is dict:
                assert testing_user['surname'] is not RESTRICTED
                assert testing_user['surname'] is not None
                assert testing_user['surname'] == caller.surname
            else:
                assert testing_user.surname is not RESTRICTED 
                assert testing_user.surname is not None
                assert testing_user.surname == caller.surname
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

def test_case_7_Any_users(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,AnyPurpose,"Person","surname")
        except Exception:
            assert False
        # Test users()
        try:
            from project import users
            result = users()
            users = result['users']
            testing_user = None
            for user in users:
                if user.testid == 'ADMIN0':
                    testing_user = user
                    break
            if type(testing_user) is dict:
                assert testing_user['surname'] is not RESTRICTED
                assert testing_user['surname'] is not None
                assert testing_user['surname'] == caller.surname
            else:
                assert testing_user.surname is not RESTRICTED 
                assert testing_user.surname is not None
                assert testing_user.surname == caller.surname
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 8: Read other Person’s name
# on endpoint users() 
# Should pass
def test_case_8_Functional_users(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    target = Person.query.filter(Person.testid == 'p1').one() 
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(target,FunctionalPurpose,"Person","name")
        except Exception:
            assert False
        # Test users()
        try:
            from project import users
            result = users()
            users = result['users']
            testing_user = None
            for user in users:
                if user.testid == target.testid:
                    testing_user = user
                    break
            if type(testing_user) is dict:
                assert testing_user['name'] is not RESTRICTED
                assert testing_user['name'] is not None
                assert testing_user['name'] == 'p1'
            else:
                assert testing_user.name is not RESTRICTED 
                assert testing_user.name is not None
                assert testing_user.name == 'p1'
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

def test_case_8_Any_users(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    target = Person.query.filter(Person.testid == 'p1').one() 
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(target,AnyPurpose,"Person","name")
        except Exception:
            assert False
        # Test users()
        try:
            from project import users
            result = users()
            users = result['users']
            testing_user = None
            for user in users:
                if user.testid == target.testid:
                    testing_user = user
                    break
            if type(testing_user) is dict:
                assert testing_user['name'] is not RESTRICTED
                assert testing_user['name'] is not None
                assert testing_user['name'] == 'p1'
            else:
                assert testing_user.name is not RESTRICTED 
                assert testing_user.name is not None
                assert testing_user.name == 'p1'
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 9: Read other Person’s surname
# on endpoint users() 
# Should pass
def test_case_9_Functional_users(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    target = Person.query.filter(Person.testid == 'p1').one() 
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(target,FunctionalPurpose,"Person","surname")
        except Exception:
            assert False
        # Test users()
        try:
            from project import users
            result = users()
            users = result['users']
            testing_user = None
            for user in users:
                if user.testid == 'p1':
                    testing_user = user
                    break
            if type(testing_user) is dict:
                assert testing_user['surname'] is not RESTRICTED
                assert testing_user['surname'] is not None
                assert testing_user['surname'] == 'p1'
            else:   
                assert testing_user.surname is not RESTRICTED 
                assert testing_user.surname is not None
                assert testing_user.surname == 'p1'
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

def test_case_9_Any_users(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    target = Person.query.filter(Person.testid == 'p1').one() 
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(target,AnyPurpose,"Person","surname")
        except Exception:
            assert False
        # Test users()
        try:
            from project import users
            result = users()
            users = result['users']
            testing_user = None
            for user in users:
                if user.testid == 'p1':
                    testing_user = user
                    break
            if type(testing_user) is dict:
                assert testing_user['surname'] is not RESTRICTED
                assert testing_user['surname'] is not None
                assert testing_user['surname'] == 'p1'
            else:   
                assert testing_user.surname is not RESTRICTED 
                assert testing_user.surname is not None
                assert testing_user.surname == 'p1'
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 10: Read one’s own name
# on endpoint user() 
# Should pass
def test_case_10_Functional_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,FunctionalPurpose,"Person","name")
        except Exception:
            assert False
        # Test user()
        try:
            from project import user
            result = user(4)
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['name'] is not RESTRICTED
                assert testing_user['name'] is not None
                assert testing_user['name'] == caller.name
            else:
                assert testing_user.name is not RESTRICTED 
                assert testing_user.name is not None
                assert testing_user.name == caller.name
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

def test_case_10_Any_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,AnyPurpose,"Person","name")
        except Exception:
            assert False
        # Test user()
        try:
            from project import user
            result = user(4)
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['name'] is not RESTRICTED
                assert testing_user['name'] is not None
                assert testing_user['name'] == caller.name
            else:
                assert testing_user.name is not RESTRICTED 
                assert testing_user.name is not None
                assert testing_user.name == caller.name
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 11: Read one’s own surname
# on endpoint user() 
# Should pass
def test_case_11_Functional_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,FunctionalPurpose,"Person","surname")
        except Exception:
            assert False
        # Test user()
        try:
            from project import user
            result = user(4)
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['surname'] is not RESTRICTED
                assert testing_user['surname'] is not None
                assert testing_user['surname'] == caller.surname
            else:
                assert testing_user.surname is not RESTRICTED 
                assert testing_user.surname is not None
                assert testing_user.surname == caller.name
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

def test_case_11_Any_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,AnyPurpose,"Person","surname")
        except Exception:
            assert False
        # Test user()
        try:
            from project import user
            result = user(4)
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['surname'] is not RESTRICTED
                assert testing_user['surname'] is not None
                assert testing_user['surname'] == caller.surname
            else:
                assert testing_user.surname is not RESTRICTED 
                assert testing_user.surname is not None
                assert testing_user.surname == caller.name
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 12: Read other Person’s name
# on endpoint user() 
# Should pass
def test_case_12_Functional_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    target = Person.query.get(5)
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(target,FunctionalPurpose,"Person","name")
        except Exception:
            assert False
        # Test user()
        try:
            from project import user
            result = user(5)
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['name'] is not RESTRICTED
                assert testing_user['name'] is not None
                assert testing_user['name'] == 'p1'
            else:
                assert testing_user.name is not RESTRICTED 
                assert testing_user.name is not None
                assert testing_user.name == 'p1'
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

def test_case_12_Any_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    target = Person.query.get(5)
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(target,AnyPurpose,"Person","name")
        except Exception:
            assert False
        # Test user()
        try:
            from project import user
            result = user(5)
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['name'] is not RESTRICTED
                assert testing_user['name'] is not None
                assert testing_user['name'] == 'p1'
            else:
                assert testing_user.name is not RESTRICTED 
                assert testing_user.name is not None
                assert testing_user.name == 'p1'
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 13: Read other Person’s surname
# on endpoint user() 
# Should pass
def test_case_13_Functional_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    target = Person.query.get(5)
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(target,FunctionalPurpose,"Person","surname")
        except Exception:
            assert False
        # Test user()
        try:
            from project import user
            result = user(5)
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['surname'] is not RESTRICTED
                assert testing_user['surname'] is not None
                assert testing_user['surname'] == 'p1'
            else:
                assert testing_user.surname is not RESTRICTED 
                assert testing_user.surname is not None
                assert testing_user.surname == 'p1'
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

def test_case_13_Any_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    target = Person.query.get(5)
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(target,AnyPurpose,"Person","surname")
        except Exception:
            assert False
        # Test user()
        try:
            from project import user
            result = user(5)
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['surname'] is not RESTRICTED
                assert testing_user['surname'] is not None
                assert testing_user['surname'] == 'p1'
            else:
                assert testing_user.surname is not RESTRICTED 
                assert testing_user.surname is not None
                assert testing_user.surname == 'p1'
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 14: Read one’s own role
# on endpoint user() 
# Should pass
def test_case_14_Functional_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,FunctionalPurpose,"Person","role")
        except Exception:
            assert False
        # Test user()
        try:
            from project import user
            result = user(4)
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['role'] is not RESTRICTED
                assert testing_user['role'] is not None
                assert testing_user['role']['name'] == caller.role.name
            else:
                assert testing_user.role is not RESTRICTED 
                assert testing_user.role is not None
                assert testing_user.role.name == caller.role.name
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

def test_case_14_Any_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,AnyPurpose,"Person","role")
        except Exception:
            assert False
        # Test user()
        try:
            from project import user
            result = user(4)
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['role'] is not RESTRICTED
                assert testing_user['role'] is not None
                assert testing_user['role']['name'] == caller.role.name
            else:
                assert testing_user.role is not RESTRICTED 
                assert testing_user.role is not None
                assert testing_user.role.name == caller.role.name
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 15: Read other Person’s role
# on endpoint user() 
# Should pass
def test_case_15_Functional_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    target = Person.query.get(5)
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(target,FunctionalPurpose,"Person","role")
        except Exception:
            assert False
        # Test user()
        try:
            from project import user
            result = user(5)
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['role'] is not RESTRICTED
                assert testing_user['role'] is not None
                assert testing_user['role']['name'] == 'REGULARUSER'
            else:
                assert testing_user.role is not RESTRICTED 
                assert testing_user.role is not None
                assert testing_user.role.name == 'REGULARUSER'
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

def test_case_15_Any_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    target = Person.query.get(5)
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(target,AnyPurpose,"Person","role")
        except Exception:
            assert False
        # Test user()
        try:
            from project import user
            result = user(5)
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['role'] is not RESTRICTED
                assert testing_user['role'] is not None
                assert testing_user['role']['name'] == 'REGULARUSER'
            else:
                assert testing_user.role is not RESTRICTED 
                assert testing_user.role is not None
                assert testing_user.role.name == 'REGULARUSER'
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 16: Read one’s own gender
# on endpoint user() 
# Should pass
def test_case_16_Functional_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,FunctionalPurpose,"Person","gender")
        except Exception:
            assert False
        # Test user()
        try:
            from project import user
            result = user(4)
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['gender'] is not RESTRICTED
                assert testing_user['gender'] is not None
                assert testing_user['gender'] == caller.gender
            else:
                assert testing_user.gender is not RESTRICTED 
                assert testing_user.gender is not None
                assert testing_user.gender == caller.gender
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()
            
def test_case_16_Any_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,AnyPurpose,"Person","gender")
        except Exception:
            assert False
        # Test user()
        try:
            from project import user
            result = user(4)
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['gender'] is not RESTRICTED
                assert testing_user['gender'] is not None
                assert testing_user['gender'] == caller.gender
            else:
                assert testing_user.gender is not RESTRICTED 
                assert testing_user.gender is not None
                assert testing_user.gender == caller.gender
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 17: Read other Person’s gender
# on endpoint user() 
# Should pass
def test_case_17_Functional_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    target = Person.query.get(5)
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(target,FunctionalPurpose,"Person","gender")
        except Exception:
            assert False
        # Test user()
        try:
            from project import user
            result = user(5)
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['gender'] is not RESTRICTED
                assert testing_user['gender'] is not None
            else:
                assert testing_user.gender is not RESTRICTED 
                assert testing_user.gender == 'male'
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 17: Read other Person’s gender
# on endpoint user() 
# Should pass
def test_case_17_Any_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    target = Person.query.get(5)
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(target,AnyPurpose,"Person","gender")
        except Exception:
            assert False
        # Test user()
        try:
            from project import user
            result = user(5)
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['gender'] is not RESTRICTED
                assert testing_user['gender'] is not None
            else:
                assert testing_user.gender is not RESTRICTED 
                assert testing_user.gender == 'male'
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 18: Read one’s own email
# on endpoint user() 
# Should pass
def test_case_18_Functional_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,FunctionalPurpose,"Person","email")
        except Exception:
            assert False
        # Test user()
        try:
            from project import user
            result = user(4)
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['email'] is not RESTRICTED
                assert testing_user['email'] is not None
                assert testing_user['email'] == caller.email
            else:
                assert testing_user.email is not RESTRICTED 
                assert testing_user.email is not None
                assert testing_user.email == caller.email
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 18: Read one’s own email
# on endpoint user() 
# Should pass
def test_case_18_Any_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,AnyPurpose,"Person","email")
        except Exception:
            assert False
        # Test user()
        try:
            from project import user
            result = user(4)
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['email'] is not RESTRICTED
                assert testing_user['email'] is not None
                assert testing_user['email'] == caller.email
            else:
                assert testing_user.email is not RESTRICTED 
                assert testing_user.email is not None
                assert testing_user.email == caller.email
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 20: Read other Person’s email (caller: moderator, this person subscribes)
# on endpoint user() 
# Should pass
def test_case_20_Functional_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR1').one()
    target = Person.query.get(5)
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(target,FunctionalPurpose,"Person","email")
        except Exception:
            assert False
        # Test user()
        try:
            from project import user
            result = user(5)
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['email'] is not RESTRICTED
                assert testing_user['email'] is not None
                assert testing_user['email'] == 'p1@gmail.com'
            else:
                assert testing_user.email is not RESTRICTED
                assert testing_user.email is not None
                assert testing_user.email == 'p1@gmail.com' 
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 20: Read other Person’s email (caller: moderator, this person subscribes)
# on endpoint user() 
# Should pass
def test_case_20_Any_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR1').one()
    target = Person.query.get(5)
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(target,AnyPurpose,"Person","email")
        except Exception:
            assert False
        # Test user()
        try:
            from project import user
            result = user(5)
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['email'] is not RESTRICTED
                assert testing_user['email'] is not None
                assert testing_user['email'] == 'p1@gmail.com'
            else:
                assert testing_user.email is not RESTRICTED
                assert testing_user.email is not None
                assert testing_user.email == 'p1@gmail.com' 
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 21: Read one’s own subscriptions
# on endpoint user() 
# Should pass
def test_case_21_Functional_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,FunctionalPurpose,"Person","subscriptions")
        except Exception:
            assert False
        # Test user()
        try:
            from project import user
            result = user(4)
            testing_user = result['user']
            assert testing_user.subscriptions is not RESTRICTED
            assert len(testing_user.subscriptions) == 2
            assert set([category.id for category in testing_user.subscriptions]) == {18, 19}
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 21: Read one’s own subscriptions
# on endpoint user() 
# Should pass
def test_case_21_Any_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,AnyPurpose,"Person","subscriptions")
        except Exception:
            assert False
        # Test user()
        try:
            from project import user
            result = user(4)
            testing_user = result['user']
            assert testing_user.subscriptions is not RESTRICTED
            assert len(testing_user.subscriptions) == 2
            assert set([category.id for category in testing_user.subscriptions]) == {18, 19}
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()


# Test Case 23: Read one’s own subscribed Category’s name
# on endpoint user() 
# Should pass
def test_case_23_Functional_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,FunctionalPurpose,"Person","subscriptions")
        except Exception:
            assert False
        # Test user()
        try:
            from project import user
            result = user(4)
            testing_user = result['user']
            assert testing_user.subscriptions is not RESTRICTED
            assert len(testing_user.subscriptions) == 2
            assert set([category.name for category in testing_user.subscriptions]) == {'c1', 'c2'}
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 23: Read one’s own subscribed Category’s name
# on endpoint user() 
# Should pass
def test_case_23_Any_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,AnyPurpose,"Person","subscriptions")
        except Exception:
            assert False
        # Test user()
        try:
            from project import user
            result = user(4)
            testing_user = result['user']
            assert testing_user.subscriptions is not RESTRICTED
            assert len(testing_user.subscriptions) == 2
            assert set([category.name for category in testing_user.subscriptions]) == {'c1', 'c2'}
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 30: Read one’s own attends events
# on endpoint profile() 
# Should pass
def test_case_30_FUNCTIONAL_profile(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,FunctionalPurpose,"Person","attends")
        except Exception:
            assert False
        # Test profile()
        try:
            from project import profile
            result = profile()
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['attends'] is not RESTRICTED
                assert len(testing_user['attends']) == 2
                assert set([event.id for event in testing_user['attends']]) == {9, 10}
            else:
                assert testing_user.attends is not RESTRICTED
                assert len(testing_user.attends) == 2
                assert set([event.id for event in testing_user.attends]) == {9, 10}
        except PrivacyException:
            assert False

# Test Case 30: Read one’s own attends events
# on endpoint profile() 
# Should pass
def test_case_30_ANY_profile(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,AnyPurpose,"Person","attends")
        except Exception:
            assert False
        # Test profile()
        try:
            from project import profile
            result = profile()
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['attends'] is not RESTRICTED
                assert len(testing_user['attends']) == 2
                assert set([event.id for event in testing_user['attends']]) == {9, 10}
            else:
                assert testing_user.attends is not RESTRICTED
                assert len(testing_user.attends) == 2
                assert set([event.id for event in testing_user.attends]) == {9, 10}
        except PrivacyException:
            assert False

# Test Case 34: Read one’s own subscriptions
# on endpoint profile() 
# Should pass
def test_case_34_Functional_profile(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,FunctionalPurpose,"Person","subscriptions")
        except Exception:
            assert False
        # Test profile()
        try:
            from project import profile
            result = profile()
            testing_subscriptions = result['subs']
            assert testing_subscriptions is not RESTRICTED
            assert len(testing_subscriptions) == 2
            assert set([category.id for category in testing_subscriptions]) == {18, 19}
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 34: Read one’s own subscriptions
# on endpoint profile() 
# Should pass
def test_case_34_Any_profile(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,AnyPurpose,"Person","subscriptions")
        except Exception:
            assert False
        # Test profile()
        try:
            from project import profile
            result = profile()
            testing_subscriptions = result['subs']
            assert testing_subscriptions is not RESTRICTED
            assert len(testing_subscriptions) == 2
            assert set([category.id for category in testing_subscriptions]) == {18, 19}
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

