"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user, AnonymousUserMixin
from flask_user import current_user
from model import db
from project import *
from dto import RESTRICTED
from flask_principal import Identity, identity_changed, AnonymousIdentity
from implicits import implicits

# This test suite is dedicated for PRIVACY tests.

def is_response(result):
    return type(result) == Response
    
@implicits("app_with_data")
def login_user(user, app_with_data):
    from flask_login import login_user
    login_user(user)
    identity_changed.send(app_with_data, identity=Identity(current_user.id))

# Test Case 6: Read one’s own name
# on endpoint users() 
# Should fail
def test_case_6_users(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test users()
        try:
            from project import users
            result = users()
            users = result['users']
            testing_user = None
            for user in users:
                if user.testid == 'ADMIN0':
                    testing_user = user
                    break
            if type(testing_user) is dict:
                assert testing_user['name'] is RESTRICTED
            else:
                assert testing_user.name is RESTRICTED
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 8: Read other Person’s name
# on endpoint users() 
# Should fail
def test_case_8_users(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test users()
        try:
            from project import users
            result = users()
            users = result['users']
            testing_user = None
            for user in users:
                if user.testid == 'p1':
                    testing_user = user
                    break
            if type(testing_user) is dict:
                assert testing_user['name'] is RESTRICTED
            else:
                assert testing_user.name is RESTRICTED
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 21: Read one’s own subscriptions
# on endpoint user() 
# Should fail
def test_case_21_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test user()
        try:
            from project import user
            result = user(4)
            testing_user = result['user']
            if type(testing_user) is dict:
                assert testing_user['subscriptions'] is RESTRICTED or len(testing_user['subscriptions']) == 0
            else:
                assert testing_user.subscriptions is RESTRICTED or len(testing_user.subscriptions) == 0
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()


