"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user, AnonymousUserMixin
from flask_user import current_user
from model import db
from project import *
from dto import RESTRICTED
from flask_principal import Identity, identity_changed, AnonymousIdentity
from implicits import implicits
from werkzeug.datastructures import MultiDict

# This test suite is dedicated for users with MODERATOR role
# Tests that are applicable to MODERATOR role.

def is_response(result):
    return type(result) == Response
    
@implicits("app_with_data")
def login_user(user, app_with_data):
    from flask_login import login_user
    login_user(user)
    identity_changed.send(app_with_data, identity=Identity(current_user.id))

# Test Case 294: Read a Category’s subscribers’s surname as the moderator of the category
# on endpoint view_category() 
# Should fail
def test_case_294_view_category(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test view_category()
        try:
            from project import view_category
            result = view_category(13) 
            testing_category = result['category']
            assert testing_category.subscribers is not RESTRICTED
            assert len(testing_category.subscribers) == 1
            assert testing_category.subscribers[0].surname is RESTRICTED
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 318: Read a Category’s events’s owner’s name as non-moderator, as manager
# on endpoint view_category() 
# Should fail
def test_case_318_view_category(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test view_category()
        try:
            from project import view_category
            result = view_category(14)  
            testing_category = result['category']
            assert testing_category.events is not RESTRICTED
            assert len(testing_category.events) == 7
            assert testing_category.events[0].owner is RESTRICTED or testing_category.events[0].owner.name is RESTRICTED
            assert testing_category.events[1].owner is RESTRICTED or testing_category.events[1].owner.name is RESTRICTED
            assert testing_category.events[2].owner is RESTRICTED or testing_category.events[2].owner.name is RESTRICTED
            assert testing_category.events[3].owner is RESTRICTED or testing_category.events[3].owner.name is RESTRICTED
            assert testing_category.events[4].owner is RESTRICTED or testing_category.events[4].owner.name is RESTRICTED
            assert testing_category.events[5].owner is RESTRICTED or testing_category.events[5].owner.name is RESTRICTED
            assert testing_category.events[6].owner is RESTRICTED or testing_category.events[6].owner.name is RESTRICTED
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 325: Read a Category’s events’s owner’s surname as non-moderator, as attendant
# on endpoint view_category() 
# Should fail
def test_case_325_view_category(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test view_category()
        try:
            from project import view_category
            result = view_category(14)  
            testing_category = result['category']
            assert testing_category.events is not RESTRICTED
            assert len(testing_category.events) == 7
            assert testing_category.events[0].owner is RESTRICTED or testing_category.events[0].owner.surname is RESTRICTED
            assert testing_category.events[1].owner is RESTRICTED or testing_category.events[1].owner.surname is RESTRICTED
            assert testing_category.events[2].owner is RESTRICTED or testing_category.events[2].owner.surname is RESTRICTED
            assert testing_category.events[3].owner is RESTRICTED or testing_category.events[3].owner.surname is RESTRICTED
            assert testing_category.events[4].owner is RESTRICTED or testing_category.events[4].owner.surname is RESTRICTED
            assert testing_category.events[5].owner is RESTRICTED or testing_category.events[5].owner.surname is RESTRICTED
            assert testing_category.events[6].owner is RESTRICTED or testing_category.events[6].owner.surname is RESTRICTED
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

