"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user, AnonymousUserMixin
from flask_user import current_user
from model import *
from project import *
from dto import RESTRICTED
from flask_principal import Identity, identity_changed, AnonymousIdentity
from implicits import implicits
from werkzeug.datastructures import MultiDict

# This test suite is dedicated for PRIVACY tests.

PURPOSES = [
    AnyPurpose,
    FunctionalPurpose,
    MarketingPurpose,
    AnalyticsPurpose,
    CorePurpose,
    RecommendEventsPurpose,
    TargetedMarketingPurpose,
    MassMarketingPurpose
]

def revoke_consent(user,purpose,resource,subresource):
    my_purpose = Purpose.query.filter_by(name=purpose).first()
    consents = Consent.query.filter_by(person_id=user.id, purpose_id=my_purpose.id, classname=resource, propertyname=subresource).all()
    for consent in consents:
        db.session.delete(consent)

def grant_consent(user,purpose,resource,subresource):
    my_purpose = Purpose.query.filter_by(name=purpose).first()
    db.session.add(Consent(classname=resource,propertyname=subresource,user=user,purpose=my_purpose))
    db.session.commit()

def is_response(result):
    return type(result) == Response
    
@implicits("app_with_data")
def login_user(user, app_with_data):
    from flask_login import login_user
    login_user(user)
    identity_changed.send(app_with_data, identity=Identity(current_user.id))

# Test Case 43: Initialize one’s own name from None to something
# on endpoint update_user()
# Should pass
def test_case_43_update_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","name")
        except Exception:
            assert False
        request.form = MultiDict({
            "id": caller.id,
            "name": "UpdatedName",
            "surname": caller.surname,
            "role": caller.role.name,
            "email": caller.email,
            "gender": caller.gender
        })
        try:
            from project import update_user
            update_user()
        except PrivacyException:
            assert False
        finally:
            assert Person.query.get(caller.id).name == "UpdatedName"
            db.session.rollback()

# Test Case 44: Edit one’s own name from something to something else
# on endpoint update_user()
# Should pass
def test_case_44_update_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN44').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","name")
        except Exception:
            assert False
        request.form = MultiDict({
            "id": caller.id,
            "name": "NewName",
            "surname": caller.surname,
            "role": caller.role.name,
            "email": caller.email,
            "gender": caller.gender
        })
        try:
            from project import update_user
            update_user()
            assert Person.query.get(caller.id).name == "NewName"
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 45: Initialize one’s own surname from None to something
# on endpoint update_user()
# Should pass
def test_case_45_update_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","surname")
        except Exception:
            assert False
        request.form = MultiDict({
            "id": caller.id,
            "name": caller.name,
            "surname": "UpdatedSurname",
            "role": caller.role.name,
            "email": caller.email,
            "gender": caller.gender
        })
        try:
            from project import update_user
            update_user()
            assert Person.query.get(caller.id).surname == "UpdatedSurname"
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 46: Edit one’s own surname from something to something else
# on endpoint update_user()
# Should pass
def test_case_46_update_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN46').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","surname")
        except Exception:
            assert False
        request.form = MultiDict({
            "id": caller.id,
            "name": caller.name,
            "surname": "NewSurname",
            "role": caller.role.name,
            "email": caller.email,
            "gender": caller.gender
        })
        try:
            from project import update_user
            update_user()
            assert Person.query.get(caller.id).surname == "NewSurname"
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 55: Edit one’s own role from Admin to Regularuser
# on endpoint update_user()
# Should pass
def test_case_55_update_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN55').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","role")
        except Exception:
            assert False
        request.form = MultiDict({
            "id": caller.id,
            "name": caller.name,
            "surname": caller.surname,
            "role": "REGULARUSER",
            "email": caller.email,
            "gender": caller.gender
        })
        try:
            from project import update_user
            update_user()
            assert Person.query.get(caller.id).role.name == "REGULARUSER"
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 56: Edit one’s own role from Admin to Moderator
# on endpoint update_user()
# Should pass
def test_case_56_update_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN56').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","role")
        except Exception:
            assert False
        request.form = MultiDict({
            "id": caller.id,
            "name": caller.name,
            "surname": caller.surname,
            "role": "MODERATOR",
            "email": caller.email,
            "gender": caller.gender
        })
        try:
            from project import update_user
            update_user()
            assert Person.query.get(caller.id).role.name == "MODERATOR"
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 57: Edit other Person’s role from Regularuser to Moderator
# on endpoint update_user()
# Should pass
def test_case_57_update_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    target = Person.query.filter(Person.testid == 'FREEUSER57').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(target,CorePurpose,"Person","role")
        except Exception:
            assert False
        request.form = MultiDict({
            "id": target.id,
            "name": target.name,
            "surname": target.surname,
            "role": "MODERATOR",
            "email": target.email,
            "gender": target.gender
        })
        try:
            from project import update_user
            update_user()
            assert Person.query.get(target.id).role.name == "MODERATOR"
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 58: Edit other Person’s role from Regularuser to Admin
# on endpoint update_user()
# Should pass
def test_case_58_update_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    target = Person.query.filter(Person.testid == 'FREEUSER58').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(target,CorePurpose,"Person","role")
        except Exception:
            assert False
        request.form = MultiDict({
            "id": target.id,
            "name": target.name,
            "surname": target.surname,
            "role": "ADMIN",
            "email": target.email,
            "gender": target.gender
        })
        try:
            from project import update_user
            update_user()
            assert Person.query.get(target.id).role.name == "ADMIN"
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 59: Edit other Person’s role from Moderator to Regularuser
# on endpoint update_user()
# Should pass
def test_case_59_update_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    target = Person.query.filter(Person.testid == 'MODERATOR59').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(target,CorePurpose,"Person","role")
        except Exception:
            assert False
        request.form = MultiDict({
            "id": target.id,
            "name": target.name,
            "surname": target.surname,
            "role": "REGULARUSER",
            "email": target.email,
            "gender": target.gender
        })
        try:
            from project import update_user
            update_user()
            assert Person.query.get(target.id).role.name == "REGULARUSER"
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 60: Edit other Person’s role from Moderator to Admin
# on endpoint update_user()
# Should pass
def test_case_60_update_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    target = Person.query.filter(Person.testid == 'MODERATOR60').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(target,CorePurpose,"Person","role")
        except Exception:
            assert False
        request.form = MultiDict({
            "id": target.id,
            "name": target.name,
            "surname": target.surname,
            "role": "ADMIN",
            "email": target.email,
            "gender": target.gender
        })
        try:
            from project import update_user
            update_user()
            assert Person.query.get(target.id).role.name == "ADMIN"
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 61: Edit other Person’s role from Admin to Regularuser
# on endpoint update_user()
# Should pass
def test_case_61_update_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    target = Person.query.filter(Person.testid == 'ADMIN61').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(target,CorePurpose,"Person","role")
        except Exception:
            assert False
        request.form = MultiDict({
            "id": target.id,
            "name": target.name,
            "surname": target.surname,
            "role": "REGULARUSER",
            "email": target.email,
            "gender": target.gender
        })
        try:
            from project import update_user
            update_user()
            assert Person.query.get(target.id).role.name == "REGULARUSER"
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 62: Edit other Person’s role from Admin to Moderator
# on endpoint update_user()
# Should pass
def test_case_62_update_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    target = Person.query.filter(Person.testid == 'ADMIN62').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(target,CorePurpose,"Person","role")
        except Exception:
            assert False
        request.form = MultiDict({
            "id": target.id,
            "name": target.name,
            "surname": target.surname,
            "role": "MODERATOR",
            "email": target.email,
            "gender": target.gender
        })
        try:
            from project import update_user
            update_user()
            assert Person.query.get(target.id).role.name == "MODERATOR"
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()