"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user, AnonymousUserMixin
from flask_user import current_user
from dtm import *
from project import *
from instrumentation import Restrict, PrivacyException
from flask_principal import Identity, identity_changed, AnonymousIdentity
from implicits import implicits
from werkzeug.datastructures import MultiDict

RESTRICTED = Restrict()

def find_personal_data(resource, subresource):
    pds = list(PersonalData.query.all())
    for pd in pds:
        if pd.resource == resource and pd.subresource == subresource:
            return pd
    return None

def add_consent(user, purpose, resource, subresource):
    pd = find_personal_data(resource, subresource)
    p = Purpose.query.filter_by(name=purpose).first()
    c = Consent(data=pd, user=user)
    c.purposes.append(p)
    db.session.add(c)
    db.session.commit()

# This test suite is dedicated for PRIVACY tests

# Test Case 231: Remove oneself from attending an Event that one attends
# on endpoint remove_attendee() 
# Should fail
def test_case_231_remove_attendee_FUNCTIONAL(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            add_consent(caller, FUNCTIONAL, 'Person', 'attends')
        except Exception:
            assert False
        # Test remove_attendee()
        try:
            from project import remove_attendee
            remove_attendee(caller.id,12)
        except PrivacyException:
            assert False
        finally:
            assert caller.id not in [attendee.id for attendee in Event.query.get(12).attendants]
            db.session.rollback()

# Test Case 235: Remove other attendants from an Event that one manages
# on endpoint remove_attendee() 
# Should fail
def test_case_235_remove_attendee_ANY(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.get(5)
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            add_consent(owner, ANY, 'Person', 'attends')
        except Exception:
            assert False
        # Test remove_attendee()
        try:
            from project import remove_attendee
            remove_attendee(5,11)
        except PrivacyException:
            assert False
        finally:
            assert 5 not in [attendee.id for attendee in Event.query.get(11).attendants]
            db.session.rollback()

# Test Case 241: Accept an attendance request for an Event as an owner
# on endpoint accept_request() 
# Should fail
def test_case_241_accept_request_ANY(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.get(7)
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            add_consent(owner, ANY, 'Person', 'attends')
        except Exception:
            assert False
        # Test accept_request()
        try:
            from project import accept_request
            result = accept_request(7,10)
        except PrivacyException:
            assert False
        finally:
            assert 7 not in [requestor.id for requestor in Event.query.get(10).requesters]
            assert 7 in [attendee.id for attendee in Event.query.get(10).attendants]
            db.session.rollback()

