"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user, AnonymousUserMixin
from flask_user import current_user
from dtm import db
from project import *
from instrumentation import Restrict, PrivacyException
from flask_principal import Identity, identity_changed, AnonymousIdentity
from implicits import implicits
from werkzeug.datastructures import MultiDict

RESTRICTED = Restrict()

# This test suite is dedicated for PRIVACY tests

# Test Case 9: Read other Person’s surname
# on endpoint users() 
# Should fail
def test_case_9_users(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test users()
        try:
            from project import users
            result = users()
            assert result['other_user_surname'] == RESTRICTED or result['other_user_surname'] is None
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 15: Read other Person’s role
# on endpoint user() 
# Should fail
def test_case_15_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test user()
        try:
            from project import user
            result = user(5)
            assert result['user_role'] == RESTRICTED or result['user_role'] is None
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 23: Read one’s own subscribed Category’s name
# on endpoint user() 
# Should fail
def test_case_23_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test user()
        try:
            from project import user
            result = user(2)
            assert result['user_subscriptions'] == RESTRICTED
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

