"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user, AnonymousUserMixin
from flask_user import current_user
from dtm import db
from project import *
from instrumentation import Restrict, PrivacyException
from flask_principal import Identity, identity_changed, AnonymousIdentity
from implicits import implicits
from werkzeug.datastructures import MultiDict

RESTRICTED = Restrict()

# This test suite is dedicated for PRIVACY tests

# Test Case 167: Read an Event’s attendants’ name field that one manages
# on endpoint manage_event() 
# Should fail
def test_case_167_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(10)
            assert len(result['event_attendant_names']) == 0 or (
                result['event_attendant_names'][0] == RESTRICTED and
                result['event_attendant_names'][1] == RESTRICTED and
                result['event_attendant_names'][2] == RESTRICTED and
                result['event_attendant_names'][3] == RESTRICTED
            )
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 172: Read an Event’s attendants’ surname field that one manages
# on endpoint manage_event() 
# Should fail
def test_case_172_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(10)
            assert len(result['event_attendant_surnames']) == 0 or (
                result['event_attendant_surnames'][0] == RESTRICTED and
                result['event_attendant_surnames'][1] == RESTRICTED and
                result['event_attendant_surnames'][2] == RESTRICTED and
                result['event_attendant_surnames'][3] == RESTRICTED
            )
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 182: Read an Event’s managedBy’ name field that one manages
# on endpoint manage_event() 
# Should fail
def test_case_182_manage_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test manage_event()
        try:
            from project import manage_event
            result = manage_event(10)
            assert len(result['event_manager_names']) == 0 or (
                result['event_manager_names'][0] == RESTRICTED and
                result['event_manager_names'][1] == RESTRICTED and
                result['event_manager_names'][2] == RESTRICTED and
                result['event_manager_names'][3] == RESTRICTED
            )
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

