"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user
from flask_principal import Identity, identity_changed
from model import db, Person
from project import *
from dto import RESTRICTED

# This test suite is dedicated for PRIVACY tests.

# Test Case 126: Read an Event’s attendants’ name field that one manages
# on endpoint view_event() 
# Should fail
def test_case_126_view_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test view_event()
        try:
            from project import view_event
            result = view_event(9)
            testing_event = result['event']
            assert testing_event is not RESTRICTED
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 4
            assert testing_event.attendants[0].name is RESTRICTED
            assert testing_event.attendants[1].name is RESTRICTED
            assert testing_event.attendants[2].name is RESTRICTED
            assert testing_event.attendants[3].name is RESTRICTED
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 127: Read an Event’s attendants’ name field that one attends
# on endpoint view_event() 
# Should fail
def test_case_127_view_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test view_event()
        try:
            from project import view_event
            result = view_event(10)
            testing_event = result['event']
            assert testing_event is not RESTRICTED
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 4
            assert testing_event.attendants[0].name is RESTRICTED
            assert testing_event.attendants[1].name is RESTRICTED
            assert testing_event.attendants[2].name is RESTRICTED
            assert testing_event.attendants[3].name is RESTRICTED
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 132: Read an Event’s attendants’ surname field that one attends
# on endpoint view_event() 
# Should fail
def test_case_132_view_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test view_event()
        try:
            from project import view_event
            result = view_event(10)
            testing_event = result['event']
            assert testing_event is not RESTRICTED
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 4
            assert testing_event.attendants[0].surname is RESTRICTED
            assert testing_event.attendants[1].surname is RESTRICTED
            assert testing_event.attendants[2].surname is RESTRICTED
            assert testing_event.attendants[3].surname is RESTRICTED
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

