"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user, AnonymousUserMixin
from flask_user import current_user
from model import *
from project import *
from dto import RESTRICTED
from flask_principal import Identity, identity_changed, AnonymousIdentity
from implicits import implicits
from werkzeug.datastructures import MultiDict

# This test suite is dedicated for PRIVACY tests.

PURPOSES = [
    AnyPurpose,
    FunctionalPurpose,
    MarketingPurpose,
    AnalyticsPurpose,
    CorePurpose,
    RecommendEventsPurpose,
    TargetedMarketingPurpose,
    MassMarketingPurpose
]

def revoke_consent(user,purpose,resource,subresource):
    my_purpose = Purpose.query.filter_by(name=purpose).first()
    consents = Consent.query.filter_by(person_id=user.id, purpose_id=my_purpose.id, classname=resource, propertyname=subresource).all()
    for consent in consents:
        db.session.delete(consent)

def grant_consent(user,purpose,resource,subresource):
    my_purpose = Purpose.query.filter_by(name=purpose).first()
    db.session.add(Consent(classname=resource,propertyname=subresource,user=user,purpose=my_purpose))
    db.session.commit()

# Test Case 125: Read an Event’s attendants’ name field that one owns
# on endpoint view_event() 
# Should pass
def test_case_125_FUNCTIONAL_view_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,FunctionalPurpose,"Person","name")
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(15)
            testing_event = result['event']
            assert testing_event is not RESTRICTED
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 1
            assert set([attendant.name for attendant in testing_event.attendants]) == set(['ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 126: Read an Event’s attendants’ name field that one manages
# on endpoint view_event() 
# Should pass
def test_case_126_FUNCTIONAL_view_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner3 = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,FunctionalPurpose,"Person","name")
            grant_consent(owner1,FunctionalPurpose,"Person","name")
            grant_consent(owner2,FunctionalPurpose,"Person","name")
            grant_consent(owner3,FunctionalPurpose,"Person","name")
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(9)
            testing_event = result['event']
            assert testing_event is not RESTRICTED
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 4
            assert set([attendant.name for attendant in testing_event.attendants]) == set(['FREEUSER0', 'p1', 'MODERATOR0', 'ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 127: Read an Event’s attendants’ name field that one attends
# on endpoint view_event() 
# Should pass
def test_case_127_FUNCTIONAL_view_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner3 = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,FunctionalPurpose,"Person","name")
            grant_consent(owner1,FunctionalPurpose,"Person","name")
            grant_consent(owner2,FunctionalPurpose,"Person","name")
            grant_consent(owner3,FunctionalPurpose,"Person","name")
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(10)
            testing_event = result['event']
            assert testing_event is not RESTRICTED
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 4
            assert set([attendant.name for attendant in testing_event.attendants]) == set(['FREEUSER0', 'p1', 'MODERATOR0', 'ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 128: Read an Event’s attendants’ name field that one requests
# on endpoint view_event() 
# Should pass
def test_case_128_FUNCTIONAL_view_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner,FunctionalPurpose,"Person","name")
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(16)
            testing_event = result['event']
            assert testing_event is not RESTRICTED
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 1
            assert set([attendant.name for attendant in testing_event.attendants]) == set(['p1'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 129: Read an Event’s attendants’ name field that one does not own, manage, attend, or request
# on endpoint view_event() 
# Should pass
def test_case_129_FUNCTIONAL_view_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner,FunctionalPurpose,"Person","name")
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(17)
            testing_event = result['event']
            assert testing_event is not RESTRICTED
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 1
            assert set([attendant.name for attendant in testing_event.attendants]) == set(['p1'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 130: Read an Event’s attendants’ surname field that one owns
# on endpoint view_event() 
# Should pass
def test_case_130_FUNCTIONAL_view_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,FunctionalPurpose,"Person","surname")
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(15)
            testing_event = result['event']
            assert testing_event is not RESTRICTED
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 1
            assert set([attendant.surname for attendant in testing_event.attendants]) == set(['ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 131: Read an Event’s attendants’ surname field that one manages
# on endpoint view_event() 
# Should pass
def test_case_131_FUNCTIONAL_view_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner3 = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,FunctionalPurpose,"Person","surname")
            grant_consent(owner1,FunctionalPurpose,"Person","surname")
            grant_consent(owner2,FunctionalPurpose,"Person","surname")
            grant_consent(owner3,FunctionalPurpose,"Person","surname")
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(9)
            testing_event = result['event']
            assert testing_event is not RESTRICTED
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 4
            assert set([attendant.surname for attendant in testing_event.attendants]) == set(['FREEUSER0', 'p1', 'MODERATOR0', 'ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 132: Read an Event’s attendants’ surname field that one attends
# on endpoint view_event() 
# Should pass
def test_case_132_FUNCTIONAL_view_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner3 = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,FunctionalPurpose,"Person","surname")
            grant_consent(owner1,FunctionalPurpose,"Person","surname")
            grant_consent(owner2,FunctionalPurpose,"Person","surname")
            grant_consent(owner3,FunctionalPurpose,"Person","surname")
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(10)
            testing_event = result['event']
            assert testing_event is not RESTRICTED
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 4
            assert set([attendant.surname for attendant in testing_event.attendants]) == set(['FREEUSER0', 'p1', 'MODERATOR0', 'ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 133: Read an Event’s attendants’ surname field that one requests
# on endpoint view_event() 
# Should pass
def test_case_133_FUNCTIONAL_view_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner,FunctionalPurpose,"Person","surname")
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(16)
            testing_event = result['event']
            assert testing_event is not RESTRICTED
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 1
            assert set([attendant.surname for attendant in testing_event.attendants]) == set(['p1'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 134: Read an Event’s attendants’ surname field that one does not own, manage, attend, or request
# on endpoint view_event() 
# Should pass
def test_case_134_FUNCTIONAL_view_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner,FunctionalPurpose,"Person","surname")
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(17)
            testing_event = result['event']
            assert testing_event is not RESTRICTED
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 1
            assert set([attendant.surname for attendant in testing_event.attendants]) == set(['p1'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 125: Read an Event’s attendants’ name field that one owns
# on endpoint view_event() 
# Should pass
def test_case_125_ANY_view_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,AnyPurpose,"Person","name")
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(15)
            testing_event = result['event']
            assert testing_event is not RESTRICTED
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 1
            assert set([attendant.name for attendant in testing_event.attendants]) == set(['ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 126: Read an Event’s attendants’ name field that one manages
# on endpoint view_event() 
# Should pass
def test_case_126_ANY_view_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner3 = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,AnyPurpose,"Person","name")
            grant_consent(owner1,AnyPurpose,"Person","name")
            grant_consent(owner2,AnyPurpose,"Person","name")
            grant_consent(owner3,AnyPurpose,"Person","name")
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(9)
            testing_event = result['event']
            assert testing_event is not RESTRICTED
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 4
            assert set([attendant.name for attendant in testing_event.attendants]) == set(['FREEUSER0', 'p1', 'MODERATOR0', 'ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 127: Read an Event’s attendants’ name field that one attends
# on endpoint view_event() 
# Should pass
def test_case_127_ANY_view_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner3 = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,AnyPurpose,"Person","name")
            grant_consent(owner1,AnyPurpose,"Person","name")
            grant_consent(owner2,AnyPurpose,"Person","name")
            grant_consent(owner3,AnyPurpose,"Person","name")
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(10)
            testing_event = result['event']
            assert testing_event is not RESTRICTED
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 4
            assert set([attendant.name for attendant in testing_event.attendants]) == set(['FREEUSER0', 'p1', 'MODERATOR0', 'ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 128: Read an Event’s attendants’ name field that one requests
# on endpoint view_event() 
# Should pass
def test_case_128_ANY_view_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner,AnyPurpose,"Person","name")
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(16)
            testing_event = result['event']
            assert testing_event is not RESTRICTED
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 1
            assert set([attendant.name for attendant in testing_event.attendants]) == set(['p1'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 129: Read an Event’s attendants’ name field that one does not own, manage, attend, or request
# on endpoint view_event() 
# Should pass
def test_case_129_ANY_view_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner,AnyPurpose,"Person","name")
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(17)
            testing_event = result['event']
            assert testing_event is not RESTRICTED
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 1
            assert set([attendant.name for attendant in testing_event.attendants]) == set(['p1'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 130: Read an Event’s attendants’ surname field that one owns
# on endpoint view_event() 
# Should pass
def test_case_130_ANY_view_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,AnyPurpose,"Person","surname")
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(15)
            testing_event = result['event']
            assert testing_event is not RESTRICTED
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 1
            assert set([attendant.surname for attendant in testing_event.attendants]) == set(['ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 131: Read an Event’s attendants’ surname field that one manages
# on endpoint view_event() 
# Should pass
def test_case_131_ANY_view_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner3 = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,AnyPurpose,"Person","surname")
            grant_consent(owner1,AnyPurpose,"Person","surname")
            grant_consent(owner2,AnyPurpose,"Person","surname")
            grant_consent(owner3,AnyPurpose,"Person","surname")
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(9)
            testing_event = result['event']
            assert testing_event is not RESTRICTED
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 4
            assert set([attendant.surname for attendant in testing_event.attendants]) == set(['FREEUSER0', 'p1', 'MODERATOR0', 'ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 132: Read an Event’s attendants’ surname field that one attends
# on endpoint view_event() 
# Should pass
def test_case_132_ANY_view_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner3 = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,AnyPurpose,"Person","surname")
            grant_consent(owner1,AnyPurpose,"Person","surname")
            grant_consent(owner2,AnyPurpose,"Person","surname")
            grant_consent(owner3,AnyPurpose,"Person","surname")
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(10)
            testing_event = result['event']
            assert testing_event is not RESTRICTED
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 4
            assert set([attendant.surname for attendant in testing_event.attendants]) == set(['FREEUSER0', 'p1', 'MODERATOR0', 'ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 133: Read an Event’s attendants’ surname field that one requests
# on endpoint view_event() 
# Should pass
def test_case_133_ANY_view_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner,AnyPurpose,"Person","surname")
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(16)
            testing_event = result['event']
            assert testing_event is not RESTRICTED
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 1
            assert set([attendant.surname for attendant in testing_event.attendants]) == set(['p1'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 134: Read an Event’s attendants’ surname field that one does not own, manage, attend, or request
# on endpoint view_event() 
# Should pass
def test_case_134_ANY_view_event(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner,AnyPurpose,"Person","surname")
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(17)
            testing_event = result['event']
            assert testing_event is not RESTRICTED
            assert testing_event.attendants is not RESTRICTED
            assert len(testing_event.attendants) == 1
            assert set([attendant.surname for attendant in testing_event.attendants]) == set(['p1'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()