"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user, AnonymousUserMixin
from flask_user import current_user
from dtm import *
from project import *
from instrumentation import Restrict, PrivacyException
from flask_principal import Identity, identity_changed, AnonymousIdentity
from implicits import implicits
from werkzeug.datastructures import MultiDict

RESTRICTED = Restrict()

def find_personal_data(resource, subresource):
    pds = list(PersonalData.query.all())
    for pd in pds:
        if pd.resource == resource and pd.subresource == subresource:
            return pd
    return None

def add_consent(user, purpose, resource, subresource):
    pd = find_personal_data(resource, subresource)
    p = Purpose.query.filter_by(name=purpose).first()
    c = Consent(data=pd, user=user)
    c.purposes.append(p)
    db.session.add(c)
    db.session.commit()

# This test suite is dedicated for PRIVACY tests

# Test Case 319: Read a Category’s events’s owner’s name as non-moderator, as attendant
# on endpoint view_category() 
# Should fail
def test_case_319_view_category_FUNCTIONAL(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner3 = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(caller, FUNCTIONAL, 'Person', 'name')
            add_consent(owner1, FUNCTIONAL, 'Person', 'name')
            add_consent(owner2, FUNCTIONAL, 'Person', 'name')
            add_consent(owner3, FUNCTIONAL, 'Person', 'name')
        except Exception:
            assert False
        # Test view_category()
        try:
            from project import view_category
            result = view_category(14) 
            assert result['category_event_owner_names'] != RESTRICTED
            assert len(result['category_event_owner_names']) == 7
            assert set(result['category_event_owner_names']) == set(['FREEUSER0', 'MODERATOR0', 'ADMIN0', 'p0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 317: Read a Category’s events’s owner’s name as non-moderator, as owner
# on endpoint view_category() 
# Should fail
def test_case_317_view_category_ANY(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner3 = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(caller, ANY, 'Person', 'name')
            add_consent(owner1, ANY, 'Person', 'name')
            add_consent(owner2, ANY, 'Person', 'name')
            add_consent(owner3, ANY, 'Person', 'name')
        except Exception:
            assert False
        # Test view_category()
        try:
            from project import view_category
            result = view_category(14)  
            assert result['category_event_owner_names'] != RESTRICTED
            assert len(result['category_event_owner_names']) == 7
            assert set(result['category_event_owner_names']) == set(['FREEUSER0', 'MODERATOR0', 'ADMIN0', 'p0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 325: Read a Category’s events’s owner’s surname as non-moderator, as attendant
# on endpoint view_category() 
# Should fail
def test_case_325_view_category_ANY(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner3 = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(caller, ANY, 'Person', 'surname')
            add_consent(owner1, ANY, 'Person', 'surname')
            add_consent(owner2, ANY, 'Person', 'surname')
            add_consent(owner3, ANY, 'Person', 'surname')
        except Exception:
            assert False
        # Test view_category()
        try:
            from project import view_category
            result = view_category(14)  
            assert result['category_event_owner_surnames'] != RESTRICTED
            assert len(result['category_event_owner_surnames']) == 7
            assert set(result['category_event_owner_surnames']) == set(['FREEUSER0', 'MODERATOR0', 'ADMIN0', 'p0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

