"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user, AnonymousUserMixin
from flask_user import current_user
from dtm import *
from project import *
from instrumentation import Restrict, PrivacyException
from flask_principal import Identity, identity_changed, AnonymousIdentity
from implicits import implicits
from werkzeug.datastructures import MultiDict

RESTRICTED = Restrict()

def find_personal_data(resource, subresource):
    pds = list(PersonalData.query.all())
    for pd in pds:
        if pd.resource == resource and pd.subresource == subresource:
            return pd
    return None

def add_consent(user, purpose, resource, subresource):
    pd = find_personal_data(resource, subresource)
    p = Purpose.query.filter_by(name=purpose).first()
    c = Consent(data=pd, user=user)
    c.purposes.append(p)
    db.session.add(c)
    db.session.commit()

# This test suite is dedicated for PRIVACY tests

# Test Case 57: Edit other Person’s role from Regularuser to Moderator
# on endpoint update_user()
# Should fail
def test_case_57_update_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    target = Person.query.filter(Person.testid == 'FREEUSER57').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(target, CORE, 'Person', 'name')
            add_consent(target, CORE, 'Person', 'surname')
            add_consent(target, CORE, 'Person', 'email')
            add_consent(target, CORE, 'Person', 'gender')
            add_consent(target, CORE, 'Person', 'role')
        except Exception:
            assert False
        request = {
            "id": target.id,
            "name": target.name,
            "surname": target.surname,
            "role": "MODERATOR",
            "email": target.email,
            "gender": target.gender
        }
        try:
            from project import update_user
            update_user(request['id'], request['name'], request['surname'], request['email'], request['gender'], request['role'])
        except PrivacyException:
            assert False
        finally:
            assert Person.query.get(target.id).role.name == "MODERATOR"
            db.session.rollback()

# Test Case 59: Edit other Person’s role from Moderator to Regularuser
# on endpoint update_user()
# Should fail
def test_case_59_update_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    target = Person.query.filter(Person.testid == 'MODERATOR59').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(target, CORE, 'Person', 'name')
            add_consent(target, CORE, 'Person', 'surname')
            add_consent(target, CORE, 'Person', 'email')
            add_consent(target, CORE, 'Person', 'gender')
            add_consent(target, CORE, 'Person', 'role')
        except Exception:
            assert False
        request = {
            "id": target.id,
            "name": target.name,
            "surname": target.surname,
            "role": "REGULARUSER",
            "email": target.email,
            "gender": target.gender
        }
        try:
            from project import update_user
            update_user(request['id'], request['name'], request['surname'], request['email'], request['gender'], request['role'])
        except PrivacyException:
            assert False
        finally:
            assert Person.query.get(target.id).role.name == "REGULARUSER"
            db.session.rollback()

# Test Case 62: Edit other Person’s role from Admin to Moderator
# on endpoint update_user()
# Should fail
def test_case_62_update_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    target = Person.query.filter(Person.testid == 'ADMIN62').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(target, CORE, 'Person', 'name')
            add_consent(target, CORE, 'Person', 'surname')
            add_consent(target, CORE, 'Person', 'email')
            add_consent(target, CORE, 'Person', 'gender')
            add_consent(target, CORE, 'Person', 'role')
        except Exception:
            assert False
        request = {
            "id": target.id,
            "name": target.name,
            "surname": target.surname,
            "role": "MODERATOR",
            "email": target.email,
            "gender": target.gender
        }
        try:
            from project import update_user
            update_user(request['id'], request['name'], request['surname'], request['email'], request['gender'], request['role'])
        except PrivacyException:
            assert False
        finally:
            assert Person.query.get(target.id).role.name == "MODERATOR"
            db.session.rollback()