"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user, AnonymousUserMixin
from flask_user import current_user
from dtm import db
from project import *
from instrumentation import Restrict, PrivacyException
from flask_principal import Identity, identity_changed, AnonymousIdentity
from implicits import implicits
from werkzeug.datastructures import MultiDict

RESTRICTED = Restrict()

# This test suite is dedicated for PRIVACY tests

# Test Case 1: Read one’s own name
# on endpoint main() 
# Should fail
def test_case_1_main(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test main()
        try:
            from project import main
            result = main()
            assert result['name'] == RESTRICTED or result['name'] is None
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 2: Read one’s own surname
# on endpoint main() 
# Should fail
def test_case_2_main(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test main()
        try:
            from project import main
            result = main()
            assert result['surname'] == RESTRICTED or result['surname'] is None
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 6: Read one’s own name
# on endpoint users() 
# Should fail
def test_case_6_users(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test users()
        try:
            from project import users
            result = users()
            assert result['current_user_name'] == RESTRICTED or result['current_user_name'] is None
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 7: Read one’s own surname
# on endpoint users() 
# Should fail
def test_case_7_users(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test users()
        try:
            from project import users
            result = users()
            assert result['current_user_surname'] == RESTRICTED or result['current_user_surname'] is None
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 8: Read other Person’s name
# on endpoint users() 
# Should fail
def test_case_8_users(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test users()
        try:
            from project import users
            result = users()
            assert result['other_user_name'] == RESTRICTED or result['other_user_name'] is None
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 9: Read other Person’s surname
# on endpoint users() 
# Should fail
def test_case_9_users(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test users()
        try:
            from project import users
            result = users()
            assert result['other_user_surname'] == RESTRICTED or result['other_user_surname'] is None
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 10: Read one’s own name
# on endpoint user() 
# Should fail
def test_case_10_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test user()
        try:
            from project import user
            result = user(4)
            assert result['user_name'] == RESTRICTED or result['user_name'] is None
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 11: Read one’s own surname
# on endpoint user() 
# Should fail
def test_case_11_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test user()
        try:
            from project import user
            result = user(4)
            assert result['user_surname'] == RESTRICTED or result['user_surname'] is None
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 12: Read other Person’s name
# on endpoint user() 
# Should fail
def test_case_12_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test user()
        try:
            from project import user
            result = user(5)
            assert result['user_name'] == RESTRICTED or result['user_name'] is None
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 13: Read other Person’s surname
# on endpoint user() 
# Should fail
def test_case_13_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test user()
        try:
            from project import user
            result = user(5)
            assert result['user_surname'] == RESTRICTED or result['user_surname'] is None
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 14: Read one’s own role
# on endpoint user() 
# Should fail
def test_case_14_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test user()
        try:
            from project import user
            result = user(4)
            assert result['user_role'] == RESTRICTED or result['user_role'] is None
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 15: Read other Person’s role
# on endpoint user() 
# Should fail
def test_case_15_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test user()
        try:
            from project import user
            result = user(5)
            assert result['user_role'] == RESTRICTED or result['user_role'] is None
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 16: Read one’s own gender
# on endpoint user() 
# Should fail
def test_case_16_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test user()
        try:
            from project import user
            result = user(4)
            assert result['user_gender'] == RESTRICTED or result['user_gender'] is None
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 17: Read other Person’s gender
# on endpoint user() 
# Should fail
def test_case_17_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test user()
        try:
            from project import user
            result = user(5)
            assert result['user_gender'] == RESTRICTED or result['user_gender'] is None
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 18: Read one’s own email
# on endpoint user() 
# Should fail
def test_case_18_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test user()
        try:
            from project import user
            result = user(4)
            assert result['user_email'] == RESTRICTED or result['user_email'] is None
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()            

# Test Case 20: Read other Person’s email (caller: moderator, this person subscribes)
# on endpoint user() 
# Should fail
def test_case_20_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test user()
        try:
            from project import user
            result = user(5)
            assert result['user_email'] == RESTRICTED or result['user_email'] is None
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 21: Read one’s own subscriptions
# on endpoint user() 
# Should fail
def test_case_21_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test user()
        try:
            from project import user
            result = user(2)
            assert result['user_subscriptions'] == RESTRICTED
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 23: Read one’s own subscribed Category’s name
# on endpoint user() 
# Should fail
def test_case_23_user(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test user()
        try:
            from project import user
            result = user(2)
            assert result['user_subscriptions'] == RESTRICTED
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 34: Read one’s own subscriptions
# on endpoint profile() 
# Should fail
def test_case_34_profile(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test profile()
        try:
            from project import profile
            result = profile()
            assert result['subscriptions'] == RESTRICTED
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()