"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user, AnonymousUserMixin
from flask_user import current_user
from model import *
from project import *
from dto import RESTRICTED
from flask_principal import Identity, identity_changed, AnonymousIdentity
from implicits import implicits
from werkzeug.datastructures import MultiDict

# This test suite is dedicated for PRIVACY tests.

PURPOSES = [
    AnyPurpose,
    FunctionalPurpose,
    MarketingPurpose,
    AnalyticsPurpose,
    CorePurpose,
    RecommendEventsPurpose,
    TargetedMarketingPurpose,
    MassMarketingPurpose,
    InsightsPurpose,
    StatsPurpose
]

def revoke_consent(user,purpose,resource,subresource):
    my_purpose = Purpose.query.filter_by(name=purpose).first()
    consents = Consent.query.filter_by(person_id=user.id, purpose_id=my_purpose.id, classname=resource, propertyname=subresource).all()
    for consent in consents:
        db.session.delete(consent)

def grant_consent(user,purpose,resource,subresource):
    my_purpose = Purpose.query.filter_by(name=purpose).first()
    db.session.add(Consent(classname=resource,propertyname=subresource,user=user,purpose=my_purpose))
    db.session.commit()

def is_response(result):
    return type(result) == Response
    
@implicits("app_with_data")
def login_user(user, app_with_data):
    from flask_login import login_user
    login_user(user)
    identity_changed.send(app_with_data, identity=Identity(current_user.id))

# Test Case 276: Analyze an event as a manager
# on endpoint analyze() 
# Should pass
def test_case_276_analyze(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner2 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner3 = Person.query.filter(Person.testid == 'p0').one()
    owner4 = Person.query.filter(Person.testid == 'p2').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,AnalyticsPurpose,"Person","gender")
            grant_consent(owner1,AnalyticsPurpose,"Person","gender")
            grant_consent(owner2,AnalyticsPurpose,"Person","gender")
            grant_consent(owner3,AnalyticsPurpose,"Person","gender")
            grant_consent(owner4,AnalyticsPurpose,"Person","gender")
        except Exception:
            assert False
        # Test analyze()
        try:
            from project import analyze
            result = analyze(9)  
            assert result['male'] is not RESTRICTED
            assert result['male'] == 4
            assert result['female'] is not RESTRICTED 
            assert result['female'] == 1
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 278: Analyze an event as a requester
# on endpoint analyze() 
# Should pass
def test_case_278_analyze(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'p0').one()
    owner2 = Person.query.filter(Person.testid == 'p2').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner1,AnalyticsPurpose,"Person","gender")
            grant_consent(owner2,AnalyticsPurpose,"Person","gender")
        except Exception:
            assert False
        # Test analyze()
        try:
            from project import analyze
            result = analyze(11)  
            assert result['male'] is not RESTRICTED
            assert result['male'] == 1
            assert result['female'] is not RESTRICTED 
            assert result['female'] == 1
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 265: Read a Category’s candidates’s name as the moderator of the category
# on endpoint edit_category() 
# Should pass
def test_case_265_edit_category(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner = Person.query.filter(Person.testid == 'MODERATOR1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner,CorePurpose,"Person","role")
            grant_consent(owner,CorePurpose,"Person","name")
        except Exception:
            assert False
        # Test edit_category()
        try:
            from project import edit_category
            result = edit_category(13)
            assert result is not None
            testing_candidates = result['candidates']
            assert testing_candidates is not RESTRICTED
            assert len(testing_candidates) == 1
            assert set([candidate.name for candidate in testing_candidates]) == set(['MODERATOR1'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

