"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user, AnonymousUserMixin
from flask_user import current_user
from dtm import *
from project import *
from instrumentation import Restrict, PrivacyException
from flask_principal import Identity, identity_changed, AnonymousIdentity
from implicits import implicits
from werkzeug.datastructures import MultiDict

RESTRICTED = Restrict()

def find_personal_data(resource, subresource):
    pds = list(PersonalData.query.all())
    for pd in pds:
        if pd.resource == resource and pd.subresource == subresource:
            return pd
    return None

def add_consent(user, purpose, resource, subresource):
    pd = find_personal_data(resource, subresource)
    p = Purpose.query.filter_by(name=purpose).first()
    c = Consent(data=pd, user=user)
    c.purposes.append(p)
    db.session.add(c)
    db.session.commit()

# This test suite is dedicated for PRIVACY tests

# Test Case 94: Read an Event’s owner’s name field that one owns
# on endpoint events() 
# Should fail
def test_case_94_events_FUNCTIONAL(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(caller, FUNCTIONAL, 'Person', 'name')
        except Exception:
            assert False
        # Test events()
        try:
            result = events()
            assert result['admin_own_event_owner_names'] != RESTRICTED
            assert result['admin_own_event_owner_names'] == 'ADMIN0'
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 95: Read an Event’s owner’s name field that one manages
# on endpoint events() 
# Should fail
def test_case_95_events_FUNCTIONAL(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(owner, FUNCTIONAL, 'Person', 'name')
        except Exception:
            assert False
        # Test events()
        try:
            result = events()
            assert result['manage_event_owner_names'] != RESTRICTED
            assert result['manage_event_owner_names'] == 'p1'
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 96: Read an Event’s owner’s name field that one attends
# on endpoint events() 
# Should fail
def test_case_96_events_FUNCTIONAL(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(owner, FUNCTIONAL, 'Person', 'name')
        except Exception:
            assert False
        # Test events()
        try:
            result = events()
            assert result['attend_event_owner_names'] != RESTRICTED
            assert result['attend_event_owner_names'] == 'p1'
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 97: Read an Event’s owner’s name field that one requests
# on endpoint events() 
# Should fail
def test_case_97_events_FUNCTIONAL(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(owner, FUNCTIONAL, 'Person', 'name')
        except Exception:
            assert False
        # Test events()
        try:
            result = events()
            assert result['request_event_owner_names'] != RESTRICTED
            assert result['request_event_owner_names'] == 'p1'
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 98: Read an Event’s owner’s name field that one does not own, manage, attend, or request
# on endpoint events() 
# Should fail
def test_case_98_events_FUNCTIONAL(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(owner, FUNCTIONAL, 'Person', 'name')
        except Exception:
            assert False
        # Test events()
        try:
            result = events()
            assert result['stranger_event_owner_names'] != RESTRICTED
            assert result['stranger_event_owner_names'] == 'p1'
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 94: Read an Event’s owner’s name field that one owns
# on endpoint events() 
# Should fail
def test_case_94_events_ANY(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(caller, ANY, 'Person', 'name')
        except Exception:
            assert False
        # Test events()
        try:
            result = events()
            assert result['admin_own_event_owner_names'] != RESTRICTED
            assert result['admin_own_event_owner_names'] == 'ADMIN0'
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 95: Read an Event’s owner’s name field that one manages
# on endpoint events() 
# Should fail
def test_case_95_events_ANY(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(owner, ANY, 'Person', 'name')
        except Exception:
            assert False
        # Test events()
        try:
            result = events()
            assert result['manage_event_owner_names'] != RESTRICTED
            assert result['manage_event_owner_names'] == 'p1'
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 96: Read an Event’s owner’s name field that one attends
# on endpoint events() 
# Should fail
def test_case_96_events_ANY(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(owner, ANY, 'Person', 'name')
        except Exception:
            assert False
        # Test events()
        try:
            result = events()
            assert result['attend_event_owner_names'] != RESTRICTED
            assert result['attend_event_owner_names'] == 'p1'
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 97: Read an Event’s owner’s name field that one requests
# on endpoint events() 
# Should fail
def test_case_97_events_ANY(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(owner, ANY, 'Person', 'name')
        except Exception:
            assert False
        # Test events()
        try:
            result = events()
            assert result['request_event_owner_names'] != RESTRICTED
            assert result['request_event_owner_names'] == 'p1'
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 98: Read an Event’s owner’s name field that one does not own, manage, attend, or request
# on endpoint events() 
# Should fail
def test_case_98_events_ANY(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(owner, ANY, 'Person', 'name')
        except Exception:
            assert False
        # Test events()
        try:
            result = events()
            assert result['stranger_event_owner_names'] != RESTRICTED
            assert result['stranger_event_owner_names'] == 'p1'
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

