"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user, AnonymousUserMixin
from flask_user import current_user
from model import *
from project import *
from dto import RESTRICTED
from flask_principal import Identity, identity_changed, AnonymousIdentity
from implicits import implicits
from werkzeug.datastructures import MultiDict

# This test suite is dedicated for PRIVACY tests.

PURPOSES = [
    AnyPurpose,
    FunctionalPurpose,
    MarketingPurpose,
    AnalyticsPurpose,
    CorePurpose,
    RecommendEventsPurpose,
    TargetedMarketingPurpose,
    MassMarketingPurpose
]

def revoke_consent(user,purpose,resource,subresource):
    my_purpose = Purpose.query.filter_by(name=purpose).first()
    consents = Consent.query.filter_by(person_id=user.id, purpose_id=my_purpose.id, classname=resource, propertyname=subresource).all()
    for consent in consents:
        db.session.delete(consent)

def grant_consent(user,purpose,resource,subresource):
    my_purpose = Purpose.query.filter_by(name=purpose).first()
    db.session.add(Consent(classname=resource,propertyname=subresource,user=user,purpose=my_purpose))
    db.session.commit()

def is_response(result):
    return type(result) == Response
    
@implicits("app_with_data")
def login_user(user, app_with_data):
    from flask_login import login_user
    login_user(user)
    identity_changed.send(app_with_data, identity=Identity(current_user.id))

# Test Case 260: Read a Category’s moderators’s name as the non-moderator of the category
# on endpoint edit_category() 
# Should pass
def test_case_260_edit_category(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner = Person.query.filter(Person.testid == 'MODERATOR1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner,CorePurpose,"Person","name")
        except Exception:
            assert False
        # Test edit_category()
        try:
            from project import edit_category
            result = edit_category(14) 
            assert result is not None
            testing_category = result['category']
            assert testing_category is not None
            assert testing_category.moderators is not RESTRICTED
            assert len(testing_category.moderators) == 1
            assert set([moderator.name for moderator in testing_category.moderators]) == set(['MODERATOR1'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 261: Read a Category’s moderators’s surname as the moderator of the category
# on endpoint edit_category() 
# Should pass
def test_case_261_edit_category(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","surname")
        except Exception:
            assert False
        # Test edit_category()
        try:
            from project import edit_category
            result = edit_category(13)
            assert result is not None
            testing_category = result['category']
            assert testing_category is not None
            assert testing_category.moderators is not RESTRICTED
            assert len(testing_category.moderators) == 1
            assert set([moderator.surname for moderator in testing_category.moderators]) == set(['MODERATOR0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 273: Send mass ads as a moderator of the category
# on endpoint send_mass_advertisement() 
# Should pass
def test_case_273_send_mass_advertisement(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner = Person.query.filter(Person.testid == 'p0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(owner,MassMarketingPurpose,"Person","email")
        except Exception:
            assert False
        # Test send_mass_advertisement()
        try:
            from project import send_mass_advertisement
            send_mass_advertisement(13)  
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

