"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user, AnonymousUserMixin
from flask_user import current_user
from dtm import *
from project import *
from instrumentation import Restrict, PrivacyException
from flask_principal import Identity, identity_changed, AnonymousIdentity
from implicits import implicits
from werkzeug.datastructures import MultiDict

RESTRICTED = Restrict()

def find_personal_data(resource, subresource):
    pds = list(PersonalData.query.all())
    for pd in pds:
        if pd.resource == resource and pd.subresource == subresource:
            return pd
    return None

def add_consent(user, purpose, resource, subresource):
    pd = find_personal_data(resource, subresource)
    p = Purpose.query.filter_by(name=purpose).first()
    c = Consent(data=pd, user=user)
    c.purposes.append(p)
    db.session.add(c)
    db.session.commit()

# This test suite is dedicated for PRIVACY tests

# Test Case 125: Read an Event’s attendants’ name field that one owns
# on endpoint view_event() 
# Should fail
def test_case_125_view_event_FUNCTIONAL(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(caller, FUNCTIONAL, 'Person', 'name')
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(15)
            assert result['event_attendant_names'] != RESTRICTED
            assert len(result['event_attendant_names']) == 1
            assert set(result['event_attendant_names']) == set(['ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 126: Read an Event’s attendants’ name field that one manages
# on endpoint view_event() 
# Should fail
def test_case_126_view_event_FUNCTIONAL(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner3 = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(caller, FUNCTIONAL, 'Person', 'name')
            add_consent(owner1, FUNCTIONAL, 'Person', 'name')
            add_consent(owner2, FUNCTIONAL, 'Person', 'name')
            add_consent(owner3, FUNCTIONAL, 'Person', 'name')
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(9)
            assert result['event_attendant_names'] != RESTRICTED
            assert len(result['event_attendant_names']) == 4
            assert set(result['event_attendant_names']) == set(['FREEUSER0', 'p1', 'MODERATOR0', 'ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 127: Read an Event’s attendants’ name field that one attends
# on endpoint view_event() 
# Should fail
def test_case_127_view_event_FUNCTIONAL(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner3 = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(caller, FUNCTIONAL, 'Person', 'name')
            add_consent(owner1, FUNCTIONAL, 'Person', 'name')
            add_consent(owner2, FUNCTIONAL, 'Person', 'name')
            add_consent(owner3, FUNCTIONAL, 'Person', 'name')
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(10)
            assert result['event_attendant_names'] != RESTRICTED
            assert len(result['event_attendant_names']) == 4
            assert set(result['event_attendant_names']) == set(['FREEUSER0', 'p1', 'MODERATOR0', 'ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 128: Read an Event’s attendants’ name field that one requests
# on endpoint view_event() 
# Should fail
def test_case_128_view_event_FUNCTIONAL(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(owner, FUNCTIONAL, 'Person', 'name')
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(16)
            assert result['event_attendant_names'] != RESTRICTED
            assert len(result['event_attendant_names']) == 1
            assert set(result['event_attendant_names']) == set(['p1'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 129: Read an Event’s attendants’ name field that one does not own, manage, attend, or request
# on endpoint view_event() 
# Should fail
def test_case_129_view_event_FUNCTIONAL(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(owner, FUNCTIONAL, 'Person', 'name')
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(17)
            assert result['event_attendant_names'] != RESTRICTED
            assert len(result['event_attendant_names']) == 1
            assert set(result['event_attendant_names']) == set(['p1'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 130: Read an Event’s attendants’ surname field that one owns
# on endpoint view_event() 
# Should fail
def test_case_130_view_event_FUNCTIONAL(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(caller, FUNCTIONAL, 'Person', 'surname')
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(15)
            assert result['event_attendant_surames'] != RESTRICTED
            assert len(result['event_attendant_surames']) == 1
            assert set(result['event_attendant_surames']) == set(['ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 131: Read an Event’s attendants’ surname field that one manages
# on endpoint view_event() 
# Should fail
def test_case_131_view_event_FUNCTIONAL(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner3 = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(caller, FUNCTIONAL, 'Person', 'surname')
            add_consent(owner1, FUNCTIONAL, 'Person', 'surname')
            add_consent(owner2, FUNCTIONAL, 'Person', 'surname')
            add_consent(owner3, FUNCTIONAL, 'Person', 'surname')
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(9)
            assert result['event_attendant_surames'] != RESTRICTED
            assert len(result['event_attendant_surames']) == 4
            assert set(result['event_attendant_surames']) == set(['FREEUSER0', 'p1', 'MODERATOR0', 'ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 132: Read an Event’s attendants’ surname field that one attends
# on endpoint view_event() 
# Should fail
def test_case_132_view_event_FUNCTIONAL(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner3 = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(caller, FUNCTIONAL, 'Person', 'surname')
            add_consent(owner1, FUNCTIONAL, 'Person', 'surname')
            add_consent(owner2, FUNCTIONAL, 'Person', 'surname')
            add_consent(owner3, FUNCTIONAL, 'Person', 'surname')
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(10)
            assert result['event_attendant_surames'] != RESTRICTED
            assert len(result['event_attendant_surames']) == 4
            assert set(result['event_attendant_surames']) == set(['FREEUSER0', 'p1', 'MODERATOR0', 'ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 133: Read an Event’s attendants’ surname field that one requests
# on endpoint view_event() 
# Should fail
def test_case_133_view_event_FUNCTIONAL(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(owner, FUNCTIONAL, 'Person', 'surname')
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(16)
            assert result['event_attendant_surames'] != RESTRICTED
            assert len(result['event_attendant_surames']) == 1
            assert set(result['event_attendant_surames']) == set(['p1'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 134: Read an Event’s attendants’ surname field that one does not own, manage, attend, or request
# on endpoint view_event() 
# Should fail
def test_case_134_view_event_FUNCTIONAL(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(owner, FUNCTIONAL, 'Person', 'surname')
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(17)
            assert result['event_attendant_surames'] != RESTRICTED
            assert len(result['event_attendant_surames']) == 1
            assert set(result['event_attendant_surames']) == set(['p1'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 125: Read an Event’s attendants’ name field that one owns
# on endpoint view_event() 
# Should fail
def test_case_125_view_event_ANY(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(caller, ANY, 'Person', 'name')
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(15)
            assert result['event_attendant_names'] != RESTRICTED
            assert len(result['event_attendant_names']) == 1
            assert set(result['event_attendant_names']) == set(['ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 126: Read an Event’s attendants’ name field that one manages
# on endpoint view_event() 
# Should fail
def test_case_126_view_event_ANY(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner3 = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(caller, ANY, 'Person', 'name')
            add_consent(owner1, ANY, 'Person', 'name')
            add_consent(owner2, ANY, 'Person', 'name')
            add_consent(owner3, ANY, 'Person', 'name')
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(9)
            assert result['event_attendant_names'] != RESTRICTED
            assert len(result['event_attendant_names']) == 4
            assert set(result['event_attendant_names']) == set(['FREEUSER0', 'p1', 'MODERATOR0', 'ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 127: Read an Event’s attendants’ name field that one attends
# on endpoint view_event() 
# Should fail
def test_case_127_view_event_ANY(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner3 = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(caller, ANY, 'Person', 'name')
            add_consent(owner1, ANY, 'Person', 'name')
            add_consent(owner2, ANY, 'Person', 'name')
            add_consent(owner3, ANY, 'Person', 'name')
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(10)
            assert result['event_attendant_names'] != RESTRICTED
            assert len(result['event_attendant_names']) == 4
            assert set(result['event_attendant_names']) == set(['FREEUSER0', 'p1', 'MODERATOR0', 'ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 128: Read an Event’s attendants’ name field that one requests
# on endpoint view_event() 
# Should fail
def test_case_128_view_event_ANY(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(owner, ANY, 'Person', 'name')
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(16)
            assert result['event_attendant_names'] != RESTRICTED
            assert len(result['event_attendant_names']) == 1
            assert set(result['event_attendant_names']) == set(['p1'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 129: Read an Event’s attendants’ name field that one does not own, manage, attend, or request
# on endpoint view_event() 
# Should fail
def test_case_129_view_event_ANY(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(owner, ANY, 'Person', 'name')
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(17)
            assert result['event_attendant_names'] != RESTRICTED
            assert len(result['event_attendant_names']) == 1
            assert set(result['event_attendant_names']) == set(['p1'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 130: Read an Event’s attendants’ surname field that one owns
# on endpoint view_event() 
# Should fail
def test_case_130_view_event_ANY(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(caller, ANY, 'Person', 'surname')
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(15)
            assert result['event_attendant_surames'] != RESTRICTED
            assert len(result['event_attendant_surames']) == 1
            assert set(result['event_attendant_surames']) == set(['ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 131: Read an Event’s attendants’ surname field that one manages
# on endpoint view_event() 
# Should fail
def test_case_131_view_event_ANY(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner3 = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(caller, ANY, 'Person', 'surname')
            add_consent(owner1, ANY, 'Person', 'surname')
            add_consent(owner2, ANY, 'Person', 'surname')
            add_consent(owner3, ANY, 'Person', 'surname')
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(9)
            assert result['event_attendant_surames'] != RESTRICTED
            assert len(result['event_attendant_surames']) == 4
            assert set(result['event_attendant_surames']) == set(['FREEUSER0', 'p1', 'MODERATOR0', 'ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 132: Read an Event’s attendants’ surname field that one attends
# on endpoint view_event() 
# Should fail
def test_case_132_view_event_ANY(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'FREEUSER0').one()
    owner2 = Person.query.filter(Person.testid == 'MODERATOR0').one()
    owner3 = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(caller, ANY, 'Person', 'surname')
            add_consent(owner1, ANY, 'Person', 'surname')
            add_consent(owner2, ANY, 'Person', 'surname')
            add_consent(owner3, ANY, 'Person', 'surname')
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(10)
            assert result['event_attendant_surames'] != RESTRICTED
            assert len(result['event_attendant_surames']) == 4
            assert set(result['event_attendant_surames']) == set(['FREEUSER0', 'p1', 'MODERATOR0', 'ADMIN0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 133: Read an Event’s attendants’ surname field that one requests
# on endpoint view_event() 
# Should fail
def test_case_133_view_event_ANY(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(owner, ANY, 'Person', 'surname')
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(16)
            assert result['event_attendant_surames'] != RESTRICTED
            assert len(result['event_attendant_surames']) == 1
            assert set(result['event_attendant_surames']) == set(['p1'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 134: Read an Event’s attendants’ surname field that one does not own, manage, attend, or request
# on endpoint view_event() 
# Should fail
def test_case_134_view_event_ANY(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner = Person.query.filter(Person.testid == 'p1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(owner, ANY, 'Person', 'surname')
        except Exception:
            assert False
        # Test view_event()
        try:
            from project import view_event
            result = view_event(17)
            assert result['event_attendant_surames'] != RESTRICTED
            assert len(result['event_attendant_surames']) == 1
            assert set(result['event_attendant_surames']) == set(['p1'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

