"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user, AnonymousUserMixin
from flask_user import current_user
from model import db
from project import *
from dto import RESTRICTED
from flask_principal import Identity, identity_changed, AnonymousIdentity
from implicits import implicits
from werkzeug.datastructures import MultiDict

# This test suite is dedicated for PRIVACY tests.

def is_response(result):
    return type(result) == Response
    
@implicits("app_with_data")
def login_user(user, app_with_data):
    from flask_login import login_user
    login_user(user)
    identity_changed.send(app_with_data, identity=Identity(current_user.id))

# Test Case 94: Read an Event’s owner’s name field that one owns
# Endpoint: events()
# Admin: Fail
def test_case_94_events(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test events()
        try:
            result = events()
            testing_events = result['events']
            assert testing_events is not RESTRICTED
            testing_event = None
            for event in testing_events:
                if event.id == 15:
                    testing_event = event
                    break
            assert testing_event is not None
            assert testing_event.owner is RESTRICTED or testing_event.owner.name is RESTRICTED
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 95: Read an Event’s owner’s name field that one manages
# Endpoint: events()
# Admin: Fail
def test_case_95_events(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test events()
        try:
            result = events()
            testing_events = result['events']
            assert testing_events is not RESTRICTED
            testing_event = None
            for event in testing_events:
                if event.testid == 'e2':
                    testing_event = event
                    break
            assert testing_event is not None
            assert testing_event.owner is RESTRICTED or testing_event.owner.name is RESTRICTED
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()

# Test Case 98: Read an Event’s owner’s name field that one does not own, manage, attend, or request
# Endpoint: events()
# Admin: Fail
def test_case_98_events(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        # Test events()
        try:
            result = events()
            testing_events = result['events']
            assert testing_events is not RESTRICTED
            testing_event = None
            for event in testing_events:
                if event.testid == 'e11':
                    testing_event = event
                    break
            assert testing_event is not None
            assert testing_event.owner is RESTRICTED or testing_event.owner.name is RESTRICTED
        except PrivacyException:
            assert True
        finally:
            db.session.rollback()