"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user, AnonymousUserMixin
from flask_user import current_user
from dtm import *
from project import *
from instrumentation import Restrict, PrivacyException
from flask_principal import Identity, identity_changed, AnonymousIdentity
from implicits import implicits
from werkzeug.datastructures import MultiDict

RESTRICTED = Restrict()

def find_personal_data(resource, subresource):
    pds = list(PersonalData.query.all())
    for pd in pds:
        if pd.resource == resource and pd.subresource == subresource:
            return pd
    return None

def add_consent(user, purpose, resource, subresource):
    pd = find_personal_data(resource, subresource)
    p = Purpose.query.filter_by(name=purpose).first()
    c = Consent(data=pd, user=user)
    c.purposes.append(p)
    db.session.add(c)
    db.session.commit()

# This test suite is dedicated for PRIVACY tests

# Test Case 278: Analyze an event as a requester
# on endpoint analyze() 
# Should fail
def test_case_278_analyze(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'p0').one()
    owner2 = Person.query.filter(Person.testid == 'p2').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(owner1, ANALYTICS, 'Person', 'gender')
            add_consent(owner2, ANALYTICS, 'Person', 'gender')
        except Exception:
            assert False
        # Test analyze()
        try:
            from project import analyze
            result = analyze(11)  
            assert result['male'] != RESTRICTED
            assert result['male'] == 1
            assert result['female'] != RESTRICTED 
            assert result['female'] == 1
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 279: Analyze an event as someone else
# on endpoint analyze() 
# Should fail
def test_case_279_analyze(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    owner1 = Person.query.filter(Person.testid == 'p0').one()
    owner2 = Person.query.filter(Person.testid == 'p2').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(owner1, ANALYTICS, 'Person', 'gender')
            add_consent(owner2, ANALYTICS, 'Person', 'gender')
        except Exception:
            assert False
        # Test analyze()
        try:
            from project import analyze
            result = analyze(12)  
            assert result['male'] != RESTRICTED
            assert result['male'] == 1
            assert result['female'] != RESTRICTED 
            assert result['female'] == 1
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 259: Read a Category’s moderators’s name as the moderator of the category
# on endpoint edit_category() 
# Should fail
def test_case_259_edit_category(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'MODERATOR0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:        
            add_consent(caller, CORE, 'Person', 'name')
        except Exception:
            assert False
        # Test edit_category()
        try:
            from project import edit_category
            result = edit_category(13)
            assert result['category_moderator_names'] != RESTRICTED
            assert len(result['category_moderator_names']) == 1
            assert set(result['category_moderator_names']) == set(['MODERATOR0'])
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

