"""
=====================================================================
COPYRIGHT NOTICE
Authors: Hoang Nguyen, Srdan Krstic, David Basin
University: ETH Zurich
Course: Security Engineering 
This code was generated by an automated system.
=====================================================================
"""

from typing import final
from flask import current_app, Response
from flask_login import login_user, AnonymousUserMixin
from flask_user import current_user
from model import *
from project import *
from dto import RESTRICTED
from flask_principal import Identity, identity_changed, AnonymousIdentity
from implicits import implicits
from werkzeug.datastructures import MultiDict

# This test suite is dedicated for PRIVACY tests.

PURPOSES = [
    AnyPurpose,
    FunctionalPurpose,
    MarketingPurpose,
    AnalyticsPurpose,
    CorePurpose,
    RecommendEventsPurpose,
    TargetedMarketingPurpose,
    MassMarketingPurpose,
    InsightsPurpose,
    StatsPurpose
]

def revoke_consent(user,purpose,resource,subresource):
    my_purpose = Purpose.query.filter_by(name=purpose).first()
    consents = Consent.query.filter_by(person_id=user.id, purpose_id=my_purpose.id, classname=resource, propertyname=subresource).all()
    for consent in consents:
        db.session.delete(consent)

def grant_consent(user,purpose,resource,subresource):
    my_purpose = Purpose.query.filter_by(name=purpose).first()
    db.session.add(Consent(classname=resource,propertyname=subresource,user=user,purpose=my_purpose))
    db.session.commit()

def is_response(result):
    return type(result) == Response
    
@implicits("app_with_data")
def login_user(user, app_with_data):
    from flask_login import login_user
    login_user(user)
    identity_changed.send(app_with_data, identity=Identity(current_user.id))

# Test Case 11: Accept a received invitation
# on endpoint accept_invitation()
# Should pass
def test_case_11_accept_invitation(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN0').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,CorePurpose,"Person","attends")
        except Exception:
            assert False
        # Test accept_invitation()
        try:
            from project import accept_invitation
            accept_invitation(12)  
        except PrivacyException:
            assert False
        finally:
            assert Invite.query.filter(Invite.id == 12).count() == 0
            assert caller.id in [p.id for p in Event.query.get(9).attendants]
            db.session.rollback()

# Test Case 18b: Read own attended events, less or equal to 2 attend events
# on endpoint personalized_stats()
# Should pass
def test_case_18b_personalized_stats(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,StatsPurpose,"Person","subscriptions")
        except Exception:
            assert False
        # Test personalized_stats()
        try:
            from project import personalized_stats
            result = personalized_stats(caller.id)
            testing_user = result["user"]
            assert testing_user.attends == RESTRICTED or len(testing_user.attends) == 0
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

# Test Case 20b: Read own subscriptions, less or equal to 2 attend events
# on endpoint personalized_stats()
# Should pass
def test_case_20b_personalized_stats(client, app_with_data):
    caller = Person.query.filter(Person.testid == 'ADMIN1').one()
    with app_with_data.test_request_context():
        login_user(caller)
        try:
            grant_consent(caller,StatsPurpose,"Person","subscriptions")
        except Exception:
            assert False
        # Test personalized_stats()
        try:
            from project import personalized_stats
            result = personalized_stats(caller.id)
            testing_user = result["user"]
            assert testing_user.subscriptions == RESTRICTED or len(testing_user.subscriptions) == 0
        except PrivacyException:
            assert False
        finally:
            db.session.rollback()

